-- Applied once to production.
-- Club ideas from the design mockup, not confirmed by the school: drafts until an admin publishes.
insert into public.clubs
  (name_uz, name_ru, name_en, description_uz, description_ru, description_en,
   schedule_uz, schedule_ru, schedule_en, place_uz, place_ru, place_en,
   grade_from, grade_to, sort_order, is_published)
values
  ('Shaxmat to‘garagi', 'Шахматный кружок', 'Chess club',
   'Shaxmat qoidalari, debyutlar va amaliy o‘yin. Maktab va tuman musobaqalariga tayyorgarlik.',
   'Правила, дебюты и практическая игра. Подготовка к школьным и районным турнирам.',
   'Rules, openings and practice games. Preparation for school and district tournaments.',
   'Seshanba, Juma • 15:00', 'Вторник, пятница • 15:00', 'Tuesday, Friday • 15:00',
   'Kutubxona zali', 'Зал библиотеки', 'Library hall', 2, 11, 10, false),
  ('Ingliz tili suhbat klubi', 'Разговорный клуб английского языка', 'English conversation club',
   'Og‘zaki nutqni rivojlantirish: mavzuli suhbatlar, rolli o‘yinlar va tinglab tushunish mashqlari.',
   'Развитие устной речи: тематические беседы, ролевые игры и упражнения на аудирование.',
   'Speaking practice: topic discussions, role plays and listening exercises.',
   'Chorshanba • 15:00', 'Среда • 15:00', 'Wednesday • 15:00',
   'Ingliz tili xonasi', 'Кабинет английского языка', 'English classroom', 5, 11, 20, false),
  ('Informatika va robototexnika', 'Информатика и робототехника', 'Computer science and robotics',
   'Kompyuter savodxonligi, dasturlash asoslari va robot to‘plamlari bilan amaliy mashg‘ulotlar.',
   'Компьютерная грамотность, основы программирования и практика с робототехническими наборами.',
   'Computer literacy, programming basics and hands-on work with robotics kits.',
   'Payshanba • 15:00', 'Четверг • 15:00', 'Thursday • 15:00',
   'Informatika xonasi', 'Кабинет информатики', 'Computer lab', 6, 11, 30, false),
  ('Sport to‘garagi (futbol, voleybol)', 'Спортивная секция (футбол, волейбол)', 'Sports club (football, volleyball)',
   'Umumiy jismoniy tayyorgarlik va jamoaviy o‘yinlar.',
   'Общая физическая подготовка и командные игры.',
   'General fitness training and team games.',
   'Dushanba, Shanba • 15:30', 'Понедельник, суббота • 15:30', 'Monday, Saturday • 15:30',
   'Maktab sport maydoni', 'Школьная спортплощадка', 'School sports ground', 5, 11, 40, false),
  ('Ashula va raqs', 'Песни и танцы', 'Song and dance',
   'Xalq qo‘shiqlari va zamonaviy raqs. Bayram tadbirlariga konsert dasturi tayyorlanadi.',
   'Народные песни и современный танец. Подготовка концертных номеров к праздникам.',
   'Folk songs and modern dance, preparing performances for school celebrations.',
   'Chorshanba, Shanba • 14:00', 'Среда, суббота • 14:00', 'Wednesday, Saturday • 14:00',
   'Maktab faollar zali', 'Актовый зал', 'Assembly hall', 1, 9, 50, false),
  ('Yosh kitobxonlar klubi', 'Клуб юных читателей', 'Young readers’ club',
   'Birgalikda kitob o‘qish, muhokama va she’r yodlash.',
   'Совместное чтение, обсуждение книг и заучивание стихов.',
   'Reading together, book discussions and learning poems.',
   'Juma • 14:00', 'Пятница • 14:00', 'Friday • 14:00',
   'Kutubxona', 'Библиотека', 'Library', 3, 8, 60, false);
