insert into public.textbooks
  (title_uz, grade, language, author, source, kind, section, url, sort_order, is_published)
values
('Uch ogʻa-ini botirlar', 5, 'uz', 'Xalq ogʻzaki ijodi', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/uch-og-a-ini-botirlar', 0, true),
('Otamga nimadir boʻldi', 5, 'uz', 'Isajon Sulton', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/otamga-nimadir-bo-ldi', 1, true),
('Hayrat ul-abror', 5, 'uz', 'Alisher Navoiy', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/hayrat-ul-abror', 2, true),
('Hellados', 5, 'uz', 'Nodar Dumbadze', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/hellados', 3, true),
('Oygul bilan Baxtiyor', 5, 'uz', 'Hamid Olimjon', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/oygul-bilan-baxtiyor', 4, true),
('Sariq devni minib', 5, 'uz', 'Xudoyberdi Toʻxtaboyev', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/sariq-devni-minib', 5, true),
('Zulmat ichra nur', 5, 'uz', 'Mirkarim Osim', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/zulmat-ichra-nur', 6, true),
('Dunyoning ishlari', 5, 'uz', 'Oʻtkir Hoshimov', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/dunyoning-ishlari', 7, true),
('Guliston', 5, 'uz', 'Saʼdiy Sheroziy', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/guliston', 8, true),
('Fanorchi ota', 5, 'uz', 'Oybek', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/fanorchi-ota', 9, true),
('Maugli', 5, 'uz', 'Jozef Redyard Kipling', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/maugli', 10, true),
('Hayrat ul-abror (nasriy bayon)', 5, 'uz', 'Alisher Navoiy', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/hayrat-ul-abror-nasriy-bayon', 11, true),
('Saylanma', 5, 'uz', 'Abdulla Oripov', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/saylanma-1', 12, true),
('Sahar vaqti yurak yigʻlar', 5, 'uz', 'Aʼzam Oʻktam', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/sahar-vaqti-yurak-yig-lar', 13, true),
('Sheʼrlar', 5, 'uz', 'Matnazar Abdulhakim', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/sherlar-4', 14, true),
('Oʻgʻri', 6, 'uz', 'Abdulla Qahhor', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/o-g-ri-1', 0, true),
('Shum bola', 6, 'uz', 'Gʻafur Gʻulom', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/shum-bola', 1, true),
('Yaxshilik', 6, 'uz', 'Odil Yoqubov', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/yaxshilik', 2, true),
('Dunyoning ishlari', 6, 'uz', 'Oʻtkir Hoshimov', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/dunyoning-ishlari', 3, true),
('Rahmat, xonim', 6, 'uz', 'Lengston Hyuz', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/rahmat-xonim', 4, true),
('Oʻn besh yoshli kapitan', 6, 'uz', 'Jyul Vern', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/o-n-besh-yoshli-kapitan', 5, true),
('Mallalar uyushmasi', 6, 'uz', 'Artur Konan Doyl', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/mallalar-uyushmasi', 6, true),
('Baxtli shahzoda', 6, 'uz', 'Oskar Uayld', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/baxtli-shahzoda', 7, true),
('Oqboʻyin', 7, 'uz', 'Normurod Norqobilov', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/oqbo-yin', 0, true),
('Soʻz chamani', 7, 'uz', 'Zulfiya', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/so-z-chamani', 1, true),
('Lobo', 7, 'uz', 'Ernest Seton-Tompson', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/lobo', 2, true),
('Chol va dengiz', 7, 'uz', 'Ernest Heminguey', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/chol-va-dengiz', 3, true),
('Mehrobdan chayon (roman)', 7, 'uz', 'Abdulla Qodiriy', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/mehrobdan-chayon-roman', 4, true),
('Yulduzli tunlar', 7, 'uz', 'Pirimqul Qodirov', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/yulduzli-tunlar', 5, true),
('Qiyomat qarz', 7, 'uz', 'Oʻlmas Umarbekov', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/qiyomat-qarz', 6, true),
('Navodir ush-shabob', 7, 'uz', 'Alisher Navoiy', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/navodir-ush-shabob', 7, true),
('Favoyid ul-kibar', 7, 'uz', 'Alisher Navoiy', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/favoyid-ul-kibar', 8, true),
('Nazm boʻstoni', 7, 'uz', 'Saida Zunnunova', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/nazm-bo-stoni', 9, true),
('Kuntugʻmish', 8, 'uz', 'Xalq ogʻzaki ijodi', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/kuntug-mish', 0, true),
('Jaloliddin Manguberdi', 8, 'uz', 'Maqsud Shayxzoda', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/jaloliddin-manguberdi', 1, true),
('Hijron kunlari  (Ufq. 2-kitob)', 8, 'uz', 'Said Ahmad', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/hijron-kunlari-ufq-2-kitob', 2, true),
('Chinor', 8, 'uz', 'Asqad Muxtor', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/chinor', 3, true),
('Ot egasi', 8, 'uz', 'Shukur Xolmirzayev', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/ot-egasi', 4, true),
('Omon ovchining oʻlimi', 8, 'uz', 'Shukur Xolmirzayev', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/omon-ovchining-o-limi', 5, true),
('Shubxa', 8, 'uz', 'Rabindranat Tagor', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/shubxa', 6, true),
('Saylanma', 8, 'uz', 'Toʻra Sulaymon', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/saylanma-4', 7, true),
('Alpomish', 9, 'uz', 'Xalq ogʻzaki ijodi', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/alpomish', 0, true),
('Farhod va Shirin (nasriy bayoni)', 9, 'uz', 'Alisher Navoiy', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/farhod-va-shirin-nasriy-bayoni', 1, true),
('Navoiy', 9, 'uz', 'Oybek', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/navoiy', 2, true),
('Ulugʻbek xazinasi', 9, 'uz', 'Odil Yoqubov', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/ulug-bek-xazinasi', 3, true),
('Sohibqiron', 9, 'uz', 'Abdulla Oripov', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/sohibqiron', 4, true),
('Temir xotin', 9, 'uz', 'Sharof Boshbekov', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/temir-xotin', 5, true),
('Hamlet', 9, 'uz', 'Uilyam Shekspir', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/hamlet', 6, true),
('Asrga tatigulik kun', 9, 'uz', 'Chingiz Aytmatov', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/asrga-tatigulik-kun', 7, true),
('Saylanma', 9, 'uz', 'Halima Xudoyberdiyeva', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/saylanma', 8, true),
('Goʻroʻgʻlining tugʻilishi', 10, 'uz', 'Xalq ogʻzaki ijodi', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/go-ro-g-lining-tug-ilishi', 0, true),
('Iliada', 10, 'uz', 'Homer', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/iliada', 1, true),
('Odisseya', 10, 'uz', 'Homer', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/odisseya', 2, true),
('Alpomish', 10, 'uz', 'Xalq ogʻzaki ijodi', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/alpomish', 3, true),
('Qutadgʻu bilig', 10, 'uz', 'Yusuf Xos Hojib', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/qutadg-u-bilig', 4, true),
('Saddi Iskandariy (nasriy bayon)', 10, 'uz', 'Alisher Navoiy', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/saddi-iskandariy-nasriy-bayon', 5, true),
('Don Kixot', 10, 'uz', 'Migel de Servantes', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/don-kixot', 6, true),
('Yevgeniy Onegin', 10, 'uz', 'Aleksandr Pushkin', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/yevgeniy-onegin', 7, true),
('Abulfayzxon', 10, 'uz', 'Abdurauf Fitrat', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/abulfayzxon', 8, true),
('Abulfayzxon', 10, 'uz', 'Abdurauf Fitrat', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/abulfayzxon-1', 9, true),
('Gʻarbiy frontda oʻzgarish yoʻq (Esizgina yoshligim)', 10, 'uz', 'Erix Mariya Remark', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/g-arbiy-frontda-o-zgarish-yo-q-esizgina-yoshligim', 10, true),
('Qutadgʻu bilig', 11, 'uz', 'Yusuf Xos Hojib', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/qutadg-u-bilig', 0, true),
('Qissasi Rabgʻuziy', 11, 'uz', 'Nosiriddin Rabgʻuziy', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/qissasi-rabg-uziy', 1, true),
('Saddi Iskandariy (nasriy bayon)', 11, 'uz', 'Alisher Navoiy', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/saddi-iskandariy-nasriy-bayon', 2, true),
('Abulfayzxon', 11, 'uz', 'Abdurauf Fitrat', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/abulfayzxon', 3, true),
('Kecha va kunduz', 11, 'uz', 'Abdulhamid Choʻlpon', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/kecha-va-kunduz', 4, true),
('Ruhlar isyoni', 11, 'uz', 'Erkin Vohidov', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/ruhlar-isyoni', 5, true),
('Garov', 11, 'uz', 'Anton Chexov', 'mutolaa.com — onlayn kutubxona', 'link', 'mutolaa', 'https://mutolaa.com/uz/book/garov', 6, true)
returning id;