-- Starter subject list for the timetable editor (standard school subjects; admins can edit,
-- add or delete them in admin → Fanlar). Applied once.
insert into public.subjects (name_uz, name_ru, name_en, sort_order) values
  ('Ona tili', 'Родной язык', 'Native language', 10),
  ('O‘qish', 'Чтение', 'Reading', 20),
  ('Adabiyot', 'Литература', 'Literature', 30),
  ('Matematika', 'Математика', 'Mathematics', 40),
  ('Algebra', 'Алгебра', 'Algebra', 50),
  ('Geometriya', 'Геометрия', 'Geometry', 60),
  ('Ingliz tili', 'Английский язык', 'English', 70),
  ('Rus tili', 'Русский язык', 'Russian', 80),
  ('Tarix', 'История', 'History', 90),
  ('Geografiya', 'География', 'Geography', 100),
  ('Biologiya', 'Биология', 'Biology', 110),
  ('Fizika', 'Физика', 'Physics', 120),
  ('Kimyo', 'Химия', 'Chemistry', 130),
  ('Informatika', 'Информатика', 'Computer science', 140),
  ('Atrofimizdagi olam', 'Окружающий мир', 'The world around us', 150),
  ('Tabiiy fan', 'Естествознание', 'Science', 160),
  ('Jismoniy tarbiya', 'Физкультура', 'Physical education', 170),
  ('Musiqa', 'Музыка', 'Music', 180),
  ('Tasviriy san’at', 'Изобразительное искусство', 'Art', 190),
  ('Texnologiya', 'Технология', 'Technology', 200),
  ('Chizmachilik', 'Черчение', 'Technical drawing', 210),
  ('Tarbiya', 'Воспитание', 'Upbringing', 220),
  ('Huquq', 'Право', 'Law', 230),
  ('Iqtisodiyot', 'Экономика', 'Economics', 240),
  ('Chaqiruvga qadar boshlang‘ich tayyorgarlik', 'Допризывная подготовка', 'Pre-conscription training', 250),
  ('Sinf soati', 'Классный час', 'Class hour', 260);
