-- The question bank, part 2 (scripts/seed_tests_2.py). Applied once; re-running adds the new tests again.
begin;
update public.test_questions x set topic = v.topic, difficulty = v.difficulty
from public.tests t, (values
  ('Matematika | 1-sinf: sonlar, qo‘shish va ayirish', '3 + 4 = ?', 'Qo‘shish va ayirish', 1),
  ('Matematika | 1-sinf: sonlar, qo‘shish va ayirish', '9 − 5 = ?', 'Qo‘shish va ayirish', 1),
  ('Matematika | 1-sinf: sonlar, qo‘shish va ayirish', 'Qaysi son 7 dan katta?', 'Sonlarni taqqoslash', 1),
  ('Matematika | 1-sinf: sonlar, qo‘shish va ayirish', '10 dan oldin keladigan son qaysi?', '20 gacha sonlar', 1),
  ('Matematika | 1-sinf: sonlar, qo‘shish va ayirish', '6 + 6 = ?', 'Qo‘shish va ayirish', 1),
  ('Matematika | 1-sinf: sonlar, qo‘shish va ayirish', 'Uchburchakning nechta burchagi bor?', 'Geometrik shakllar', 1),
  ('Matematika | 1-sinf: sonlar, qo‘shish va ayirish', 'Kvadratning nechta tomoni bor?', 'Geometrik shakllar', 1),
  ('Matematika | 1-sinf: sonlar, qo‘shish va ayirish', '15 − 5 = ?', 'Qo‘shish va ayirish', 1),
  ('Matematika | 1-sinf: sonlar, qo‘shish va ayirish', 'Qaysi tenglik to‘g‘ri?', 'Qo‘shish va ayirish', 1),
  ('Matematika | 1-sinf: sonlar, qo‘shish va ayirish', '2, 4, 6, … Keyingi son qaysi?', 'Sonlar ketma-ketligi', 2),
  ('Matematika | 1-sinf: sonlar, qo‘shish va ayirish', '8 + 0 = ?', 'Qo‘shish va ayirish', 1),
  ('Matematika | 1-sinf: sonlar, qo‘shish va ayirish', 'Bir haftada necha kun bor?', 'Vaqt', 1),
  ('Matematika | 1-sinf: sonlar, qo‘shish va ayirish', '12 soni nechta o‘nlik va nechta birlikdan iborat?', '20 gacha sonlar', 2),
  ('Matematika | 1-sinf: sonlar, qo‘shish va ayirish', 'Qaysi son eng kichik?', 'Sonlarni taqqoslash', 1),
  ('Matematika | 1-sinf: sonlar, qo‘shish va ayirish', 'Alida 5 ta olma bor edi. U 2 tasini yedi. Nechta olma qoldi?', 'Masalalar', 2),
  ('Matematika | 1-sinf: sonlar, qo‘shish va ayirish', '7 + 3 = 10 bo‘lsa, 10 − 3 = ?', 'Qo‘shish va ayirish', 2),
  ('Matematika | 1-sinf: sonlar, qo‘shish va ayirish', 'Doiraning nechta burchagi bor?', 'Geometrik shakllar', 1),
  ('Matematika | 1-sinf: sonlar, qo‘shish va ayirish', 'Qaysi qatorda sonlar kichigidan kattasiga qarab yozilgan?', 'Sonlarni taqqoslash', 2),
  ('Musiqa | 1-sinf: notalar va cholg‘ular', 'Nechta asosiy nota bor?', 'Notalar', 1),
  ('Musiqa | 1-sinf: notalar va cholg‘ular', '«Do, re, mi …» — keyingi nota qaysi?', 'Notalar', 1),
  ('Musiqa | 1-sinf: notalar va cholg‘ular', 'Doira qanday cholg‘u?', 'Cholg‘ular', 1),
  ('Musiqa | 1-sinf: notalar va cholg‘ular', 'Dutorning nechta tori bor?', 'Cholg‘ular', 1),
  ('Musiqa | 1-sinf: notalar va cholg‘ular', 'Karnay qanday cholg‘u?', 'Cholg‘ular', 1),
  ('Musiqa | 1-sinf: notalar va cholg‘ular', 'Qaysi biri torli cholg‘u?', 'Cholg‘ular', 1),
  ('Musiqa | 1-sinf: notalar va cholg‘ular', 'Fortepiano qanday cholg‘u?', 'Cholg‘ular', 1),
  ('Musiqa | 1-sinf: notalar va cholg‘ular', 'O‘zbekiston Respublikasi Davlat madhiyasi musiqasini kim yaratgan?', 'Davlat madhiyasi', 2),
  ('Musiqa | 1-sinf: notalar va cholg‘ular', 'Davlat madhiyasi so‘zlarining muallifi kim?', 'Davlat madhiyasi', 2),
  ('Musiqa | 1-sinf: notalar va cholg‘ular', 'Davlat madhiyasi yangraganda nima qilish kerak?', 'Davlat madhiyasi', 1),
  ('DTM mashq: Matematika (1-to‘plam)', '2⁵ ning qiymati nechaga teng?', 'Daraja va ildiz', 1),
  ('DTM mashq: Matematika (1-to‘plam)', '√144 = ?', 'Daraja va ildiz', 1),
  ('DTM mashq: Matematika (1-to‘plam)', '80 ning 15 foizi nechaga teng?', 'Foizlar', 1),
  ('DTM mashq: Matematika (1-to‘plam)', '3x − 7 = 11 tenglamaning ildizi?', 'Tenglamalar', 1),
  ('DTM mashq: Matematika (1-to‘plam)', 'x² − 5x + 6 = 0 tenglamaning ildizlari?', 'Kvadrat tenglamalar', 2),
  ('DTM mashq: Matematika (1-to‘plam)', 'log₂ 8 = ?', 'Logarifm', 2),
  ('DTM mashq: Matematika (1-to‘plam)', 'Arifmetik progressiyada a₁ = 3, d = 4. a₁₀ ni toping.', 'Progressiyalar', 2),
  ('DTM mashq: Matematika (1-to‘plam)', 'Geometrik progressiyada b₁ = 2, q = 3. b₄ ni toping.', 'Progressiyalar', 2),
  ('DTM mashq: Matematika (1-to‘plam)', 'sin 30° = ?', 'Trigonometriya', 1),
  ('DTM mashq: Matematika (1-to‘plam)', 'Uchburchak ichki burchaklarining yig‘indisi nechaga teng?', 'Planimetriya', 1),
  ('DTM mashq: Matematika (1-to‘plam)', 'To‘g‘ri burchakli uchburchakning katetlari 6 va 8 ga teng. Gipotenuzasini toping.', 'Planimetriya', 1),
  ('DTM mashq: Matematika (1-to‘plam)', 'Radiusi 5 ga teng doiraning yuzi?', 'Planimetriya', 2),
  ('DTM mashq: Matematika (1-to‘plam)', '(a + b)² ifoda nimaga teng?', 'Algebraik ifodalar', 1),
  ('DTM mashq: Matematika (1-to‘plam)', '7! / 5! = ?', 'Kombinatorika', 2),
  ('DTM mashq: Matematika (1-to‘plam)', '|−7| + |3| = ?', 'Sonlar', 1),
  ('DTM mashq: Matematika (1-to‘plam)', 'f(x) = 2x + 1 bo‘lsa, f(3) = ?', 'Funksiyalar', 1),
  ('DTM mashq: Matematika (1-to‘plam)', '0,25 ni oddiy kasr ko‘rinishida yozing.', 'Kasrlar', 1),
  ('DTM mashq: Matematika (1-to‘plam)', 'Kvadratning perimetri 20 sm. Uning yuzi qancha?', 'Planimetriya', 2),
  ('DTM mashq: Matematika (1-to‘plam)', '3/4 + 1/8 = ?', 'Kasrlar', 1),
  ('DTM mashq: Matematika (1-to‘plam)', 'y = x³ funksiyaning hosilasi?', 'Hosila', 2),
  ('DTM mashq: Matematika (1-to‘plam)', 'Qirrasi 3 sm bo‘lgan kubning hajmi?', 'Stereometriya', 1),
  ('DTM mashq: Matematika (1-to‘plam)', '48 va 36 sonlarining EKUBi?', 'Sonlar', 1),
  ('DTM mashq: Fizika (1-to‘plam)', 'Xalqaro birliklar tizimida (SI) tezlik birligi?', 'Birliklar', 1),
  ('DTM mashq: Fizika (1-to‘plam)', 'Kuch birligi qaysi?', 'Birliklar', 1),
  ('DTM mashq: Fizika (1-to‘plam)', 'Massasi 2 kg bo‘lgan jism 3 m/s² tezlanish bilan harakatlanmoqda. Unga ta’sir etuvchi kuch?', 'Dinamika', 1),
  ('DTM mashq: Fizika (1-to‘plam)', 'Erkin tushish tezlanishi taxminan nechaga teng?', 'Dinamika', 1),
  ('DTM mashq: Fizika (1-to‘plam)', 'Ish birligi qaysi?', 'Birliklar', 1),
  ('DTM mashq: Fizika (1-to‘plam)', 'Quvvat formulasi qaysi?', 'Ish va quvvat', 1),
  ('DTM mashq: Fizika (1-to‘plam)', 'Zanjir qismi uchun Om qonuni?', 'Elektr toki', 1),
  ('DTM mashq: Fizika (1-to‘plam)', 'Kuchlanish 12 V, qarshilik 4 Om. Tok kuchi?', 'Elektr toki', 1),
  ('DTM mashq: Fizika (1-to‘plam)', 'Yorug‘likning vakuumdagi tezligi taxminan?', 'Optika', 1),
  ('DTM mashq: Fizika (1-to‘plam)', 'Tovushning havodagi tezligi taxminan?', 'Tebranish va to‘lqinlar', 1),
  ('DTM mashq: Fizika (1-to‘plam)', 'Massasi 2 kg, tezligi 3 m/s bo‘lgan jismning kinetik energiyasi?', 'Energiya', 2),
  ('DTM mashq: Fizika (1-to‘plam)', 'Massasi 1 kg jism 10 m balandlikda turibdi (g = 10 m/s²). Potensial energiyasi?', 'Energiya', 2),
  ('DTM mashq: Fizika (1-to‘plam)', 'Bosim birligi qaysi?', 'Birliklar', 1),
  ('DTM mashq: Fizika (1-to‘plam)', 'Normal atmosfera bosimida suv necha gradusda qaynaydi?', 'Issiqlik', 1),
  ('DTM mashq: Fizika (1-to‘plam)', 'Absolyut nol harorati taxminan?', 'Issiqlik', 2),
  ('DTM mashq: Fizika (1-to‘plam)', 'Elektr zaryadi birligi?', 'Birliklar', 1),
  ('DTM mashq: Fizika (1-to‘plam)', 'Jism 20 m/s tezlik bilan 5 s tekis harakatlandi. Bosib o‘tgan yo‘li?', 'Kinematika', 1),
  ('DTM mashq: Fizika (1-to‘plam)', 'Zichlik formulasi?', 'Molekulyar fizika', 1),
  ('DTM mashq: Fizika (1-to‘plam)', 'Nyutonning uchinchi qonuni nima deydi?', 'Dinamika', 2),
  ('DTM mashq: Fizika (1-to‘plam)', 'Linzaning optik kuchi birligi?', 'Optika', 2),
  ('DTM mashq: Fizika (1-to‘plam)', 'Chastota birligi?', 'Birliklar', 1),
  ('DTM mashq: Kimyo (1-to‘plam)', 'Suvning kimyoviy formulasi?', 'Formulalar', 1),
  ('DTM mashq: Kimyo (1-to‘plam)', 'Osh tuzining formulasi?', 'Formulalar', 1),
  ('DTM mashq: Kimyo (1-to‘plam)', 'Kislorodning kimyoviy belgisi?', 'Kimyoviy elementlar', 1),
  ('DTM mashq: Kimyo (1-to‘plam)', 'Temirning kimyoviy belgisi?', 'Kimyoviy elementlar', 1),
  ('DTM mashq: Kimyo (1-to‘plam)', 'Natriyning tartib raqami?', 'Davriy jadval', 1),
  ('DTM mashq: Kimyo (1-to‘plam)', 'Uglerodning tartib raqami?', 'Davriy jadval', 1),
  ('DTM mashq: Kimyo (1-to‘plam)', 'Suvning (H₂O) molyar massasi?', 'Mol va molyar massa', 1),
  ('DTM mashq: Kimyo (1-to‘plam)', 'Karbonat angidridning (CO₂) molyar massasi?', 'Mol va molyar massa', 2),
  ('DTM mashq: Kimyo (1-to‘plam)', 'pH = 7 bo‘lgan eritma muhiti?', 'Eritmalar', 1),
  ('DTM mashq: Kimyo (1-to‘plam)', 'Normal sharoitda 1 mol gaz qancha hajmni egallaydi?', 'Gazlar', 2),
  ('DTM mashq: Kimyo (1-to‘plam)', 'Avogadro soni taxminan?', 'Mol va molyar massa', 2),
  ('DTM mashq: Kimyo (1-to‘plam)', 'Qaysi element inert (nodir) gaz?', 'Davriy jadval', 1),
  ('DTM mashq: Kimyo (1-to‘plam)', 'Metanning formulasi?', 'Organik kimyo', 1),
  ('DTM mashq: Kimyo (1-to‘plam)', 'Sulfat kislotaning formulasi?', 'Kislotalar', 1),
  ('DTM mashq: Kimyo (1-to‘plam)', 'Kimyoviy elementlar davriy jadvalini kim yaratgan?', 'Davriy jadval', 1),
  ('DTM mashq: Kimyo (1-to‘plam)', 'Kislorod atomida nechta elektron bor?', 'Atom tuzilishi', 1),
  ('DTM mashq: Kimyo (1-to‘plam)', 'NaOH qaysi moddalar sinfiga kiradi?', 'Asoslar', 1),
  ('DTM mashq: Kimyo (1-to‘plam)', 'Havo tarkibida qaysi gaz eng ko‘p?', 'Gazlar', 1),
  ('DTM mashq: Kimyo (1-to‘plam)', 'Olmos va grafit qaysi elementning allotropik shakllari?', 'Kimyoviy elementlar', 2),
  ('DTM mashq: Kimyo (1-to‘plam)', '2H₂ + O₂ → 2H₂O reaksiyasi qaysi turga kiradi?', 'Kimyoviy reaksiyalar', 1),
  ('DTM mashq: Kimyo (1-to‘plam)', 'Kaliyning kimyoviy belgisi?', 'Kimyoviy elementlar', 1),
  ('DTM mashq: Biologiya (1-to‘plam)', 'Hujayraning «energiya stansiyasi» qaysi organoid?', 'Hujayra', 1),
  ('DTM mashq: Biologiya (1-to‘plam)', 'Fotosintez hujayraning qaysi qismida boradi?', 'Hujayra', 1),
  ('DTM mashq: Biologiya (1-to‘plam)', 'Odamning somatik hujayralarida nechta xromosoma bor?', 'Genetika', 2),
  ('DTM mashq: Biologiya (1-to‘plam)', 'RNKda timin o‘rniga qaysi azotli asos bo‘ladi?', 'Molekulyar biologiya', 2),
  ('DTM mashq: Biologiya (1-to‘plam)', 'Odam yuragi necha kamerali?', 'Odam anatomiyasi', 1),
  ('DTM mashq: Biologiya (1-to‘plam)', 'AB0 tizimida nechta qon guruhi bor?', 'Odam anatomiyasi', 1),
  ('DTM mashq: Biologiya (1-to‘plam)', 'Oqsil sintezi hujayraning qaysi qismida boradi?', 'Hujayra', 2),
  ('DTM mashq: Biologiya (1-to‘plam)', 'Irsiyat qonunlarini kim kashf etgan?', 'Genetika', 1),
  ('DTM mashq: Biologiya (1-to‘plam)', 'Tabiiy tanlanish nazariyasini kim yaratgan?', 'Evolyutsiya', 1),
  ('DTM mashq: Biologiya (1-to‘plam)', 'Odam organizmidagi eng yirik bez?', 'Odam anatomiyasi', 1),
  ('DTM mashq: Biologiya (1-to‘plam)', 'Eritrotsitlarning asosiy vazifasi?', 'Odam anatomiyasi', 1),
  ('DTM mashq: Biologiya (1-to‘plam)', 'Qon ivishida qaysi qon hujayralari qatnashadi?', 'Odam anatomiyasi', 2),
  ('DTM mashq: Biologiya (1-to‘plam)', 'Insulin gormonini qaysi bez ishlab chiqaradi?', 'Odam anatomiyasi', 2),
  ('DTM mashq: Biologiya (1-to‘plam)', 'Hasharotlarning nechta oyog‘i bor?', 'Zoologiya', 1),
  ('DTM mashq: Biologiya (1-to‘plam)', 'O‘rgimchakning nechta oyog‘i bor?', 'Zoologiya', 1),
  ('DTM mashq: Biologiya (1-to‘plam)', 'Qaysi hayvon sutemizuvchi?', 'Zoologiya', 1),
  ('DTM mashq: Biologiya (1-to‘plam)', 'Mitoz natijasida bitta hujayradan nechta hujayra hosil bo‘ladi?', 'Hujayra', 2),
  ('DTM mashq: Biologiya (1-to‘plam)', 'Jinsiy hujayralarda (gametalarda) xromosomalar to‘plami qanday?', 'Genetika', 2),
  ('DTM mashq: Biologiya (1-to‘plam)', 'Viruslar haqidagi to‘g‘ri fikr?', 'Mikrobiologiya', 2),
  ('DTM mashq: Biologiya (1-to‘plam)', 'Katta yoshli odam skeletida taxminan nechta suyak bor?', 'Odam anatomiyasi', 1),
  ('DTM mashq: Ingliz tili (1-to‘plam)', 'She ___ a student.', 'To be', 1),
  ('DTM mashq: Ingliz tili (1-to‘plam)', 'They ___ football every Sunday.', 'Present Simple', 1),
  ('DTM mashq: Ingliz tili (1-to‘plam)', 'Choose the past form of «go».', 'Irregular verbs', 1),
  ('DTM mashq: Ingliz tili (1-to‘plam)', 'Choose the plural of «child».', 'Nouns', 1),
  ('DTM mashq: Ingliz tili (1-to‘plam)', 'I have lived here ___ 2015.', 'Present Perfect', 2),
  ('DTM mashq: Ingliz tili (1-to‘plam)', 'Choose the opposite of «big».', 'Vocabulary', 1),
  ('DTM mashq: Ingliz tili (1-to‘plam)', 'Look! He ___ TV now.', 'Present Continuous', 1),
  ('DTM mashq: Ingliz tili (1-to‘plam)', '«Kitob» in English is …', 'Vocabulary', 1),
  ('DTM mashq: Ingliz tili (1-to‘plam)', 'Choose the comparative of «good».', 'Adjectives', 2),
  ('DTM mashq: Ingliz tili (1-to‘plam)', 'There ___ many apples on the table.', 'There is / are', 1),
  ('DTM mashq: Ingliz tili (1-to‘plam)', 'If it rains, we ___ at home.', 'Conditionals', 2),
  ('DTM mashq: Ingliz tili (1-to‘plam)', '___ you speak English?', 'Modal verbs', 1),
  ('DTM mashq: Ingliz tili (1-to‘plam)', 'Choose the superlative of «beautiful».', 'Adjectives', 2),
  ('DTM mashq: Ingliz tili (1-to‘plam)', 'She has ___ apple.', 'Articles', 1),
  ('DTM mashq: Ingliz tili (1-to‘plam)', 'Choose the past participle of «write».', 'Irregular verbs', 2),
  ('DTM mashq: Ingliz tili (1-to‘plam)', '«How old are you?» — the best answer:', 'Speaking', 1),
  ('DTM mashq: Ingliz tili (1-to‘plam)', 'The letter ___ yesterday.', 'Passive voice', 3),
  ('DTM mashq: Ingliz tili (1-to‘plam)', 'I was born ___ May.', 'Prepositions', 1),
  ('DTM mashq: Ingliz tili (1-to‘plam)', 'Every day he ___ to school by bus.', 'Present Simple', 1),
  ('DTM mashq: Ingliz tili (1-to‘plam)', 'Choose the synonym of «happy».', 'Vocabulary', 1),
  ('DTM mashq: Ona tili va adabiyot (1-to‘plam)', 'Ot so‘z turkumi qaysi so‘roqlarga javob beradi?', 'So‘z turkumlari', 1),
  ('DTM mashq: Ona tili va adabiyot (1-to‘plam)', 'Sifat qaysi so‘roqlarga javob beradi?', 'So‘z turkumlari', 1),
  ('DTM mashq: Ona tili va adabiyot (1-to‘plam)', 'Fe’l qaysi so‘roqlarga javob beradi?', 'So‘z turkumlari', 1),
  ('DTM mashq: Ona tili va adabiyot (1-to‘plam)', '«Kitob» so‘zi qaysi so‘z turkumiga kiradi?', 'So‘z turkumlari', 1),
  ('DTM mashq: Ona tili va adabiyot (1-to‘plam)', '«Chiroyli» so‘zi qaysi so‘z turkumiga kiradi?', 'So‘z turkumlari', 1),
  ('DTM mashq: Ona tili va adabiyot (1-to‘plam)', '«Yugurdi» so‘zi qaysi so‘z turkumiga kiradi?', 'So‘z turkumlari', 1),
  ('DTM mashq: Ona tili va adabiyot (1-to‘plam)', 'O‘zbek tilida nechta unli tovush bor?', 'Fonetika', 1),
  ('DTM mashq: Ona tili va adabiyot (1-to‘plam)', '«Uch», «o‘n» so‘zlari qaysi so‘z turkumiga kiradi?', 'So‘z turkumlari', 1),
  ('DTM mashq: Ona tili va adabiyot (1-to‘plam)', '«Men, sen, u» so‘zlari qaysi so‘z turkumiga kiradi?', 'So‘z turkumlari', 1),
  ('DTM mashq: Ona tili va adabiyot (1-to‘plam)', 'Gapning bosh bo‘laklari?', 'Sintaksis', 1),
  ('DTM mashq: Ona tili va adabiyot (1-to‘plam)', '«Tez yurdi» birikmasida «tez» qaysi so‘z turkumi?', 'So‘z turkumlari', 2),
  ('DTM mashq: Ona tili va adabiyot (1-to‘plam)', 'Ko‘plik qo‘shimchasi qaysi?', 'Morfologiya', 1),
  ('DTM mashq: Ona tili va adabiyot (1-to‘plam)', 'Qaratqich kelishigi qo‘shimchasi qaysi?', 'Kelishiklar', 1),
  ('DTM mashq: Ona tili va adabiyot (1-to‘plam)', '«O‘tkan kunlar» romanining muallifi?', 'Adabiyot', 1),
  ('DTM mashq: Ona tili va adabiyot (1-to‘plam)', '«Xamsa» asarining muallifi?', 'Adabiyot', 1),
  ('DTM mashq: Ona tili va adabiyot (1-to‘plam)', '«Boburnoma» asarining muallifi?', 'Adabiyot', 1),
  ('DTM mashq: Ona tili va adabiyot (1-to‘plam)', '«Kecha va kunduz» romanining muallifi?', 'Adabiyot', 2),
  ('DTM mashq: O‘zbekiston tarixi (1-to‘plam)', 'O‘zbekiston Respublikasi Oliy Kengashi davlat mustaqilligini qachon e’lon qildi?', 'Mustaqillik davri', 1),
  ('DTM mashq: O‘zbekiston tarixi (1-to‘plam)', 'O‘zbekiston Respublikasining birinchi Konstitutsiyasi qachon qabul qilingan?', 'Mustaqillik davri', 1),
  ('DTM mashq: O‘zbekiston tarixi (1-to‘plam)', 'Amir Temur qaysi yili tug‘ilgan?', 'Temuriylar davri', 2),
  ('DTM mashq: O‘zbekiston tarixi (1-to‘plam)', 'Amir Temur davlatining poytaxti?', 'Temuriylar davri', 1),
  ('DTM mashq: O‘zbekiston tarixi (1-to‘plam)', 'Mirzo Ulug‘bek rasadxonasi qaysi shaharda qurilgan?', 'Temuriylar davri', 1),
  ('DTM mashq: O‘zbekiston tarixi (1-to‘plam)', 'Zahiriddin Muhammad Bobur Hindistonda qaysi sulolaga asos solgan?', 'Temuriylar davri', 2),
  ('DTM mashq: O‘zbekiston tarixi (1-to‘plam)', 'Algebra faniga asos solgan olim?', 'Allomalar', 1),
  ('DTM mashq: O‘zbekiston tarixi (1-to‘plam)', '«Tib qonunlari» asarining muallifi?', 'Allomalar', 1),
  ('DTM mashq: O‘zbekiston tarixi (1-to‘plam)', 'O‘zbekiston milliy valyutasi — so‘m to‘liq muomalaga qachon kiritilgan?', 'Mustaqillik davri', 2),
  ('DTM mashq: O‘zbekiston tarixi (1-to‘plam)', 'O‘zbekiston Birlashgan Millatlar Tashkilotiga qachon a’zo bo‘ldi?', 'Mustaqillik davri', 2),
  ('DTM mashq: O‘zbekiston tarixi (1-to‘plam)', 'Amir Temur maqbarasi qanday nomlanadi?', 'Temuriylar davri', 1),
  ('DTM mashq: O‘zbekiston tarixi (1-to‘plam)', 'Jaloliddin Manguberdi qaysi bosqinchilarga qarshi kurashgan?', 'Mo‘g‘ullar istilosi', 2),
  ('DTM mashq: O‘zbekiston tarixi (1-to‘plam)', 'Aleksandr Makedonskiyga qarshi kurash olib borgan So‘g‘d qahramoni?', 'Qadimgi davr', 2),
  ('DTM mashq: O‘zbekiston tarixi (1-to‘plam)', 'Buyuk Ipak yo‘li qaysi hududlarni bog‘lagan?', 'Qadimgi davr', 1),
  ('DTM mashq: Geografiya (1-to‘plam)', 'O‘zbekiston tarkibida Qoraqalpog‘iston Respublikasidan tashqari nechta viloyat bor?', 'O‘zbekiston ma’muriy tuzilishi', 1),
  ('DTM mashq: Geografiya (1-to‘plam)', 'Surxondaryo viloyatining markazi?', 'O‘zbekiston ma’muriy tuzilishi', 1),
  ('DTM mashq: Geografiya (1-to‘plam)', 'O‘zbekistonning eng baland nuqtasi?', 'O‘zbekiston relyefi', 2),
  ('DTM mashq: Geografiya (1-to‘plam)', 'O‘zbekiston nechta davlat bilan chegaradosh?', 'O‘zbekiston chegaralari', 1),
  ('DTM mashq: Geografiya (1-to‘plam)', 'Orol dengiziga qaysi daryolar quyiladi?', 'O‘zbekiston suvlari', 1),
  ('DTM mashq: Geografiya (1-to‘plam)', 'Qizilqum cho‘li qaysi daryolar oralig‘ida joylashgan?', 'O‘zbekiston relyefi', 2),
  ('DTM mashq: Geografiya (1-to‘plam)', 'Yer yuzidagi eng katta okean?', 'Dunyo okeani', 1),
  ('DTM mashq: Geografiya (1-to‘plam)', 'Eng katta materik?', 'Materiklar', 1),
  ('DTM mashq: Geografiya (1-to‘plam)', 'Ekvatorning uzunligi taxminan?', 'Yer shari', 2),
  ('DTM mashq: Geografiya (1-to‘plam)', 'O‘zbekiston iqlimi qanday?', 'Iqlim', 1),
  ('DTM mashq: Geografiya (1-to‘plam)', 'Yer o‘z o‘qi atrofida qancha vaqtda bir marta aylanadi?', 'Yer shari', 1),
  ('DTM mashq: Geografiya (1-to‘plam)', 'O‘zbekistonning poytaxti?', 'O‘zbekiston ma’muriy tuzilishi', 1)
) as v (title, question, topic, difficulty)
where t.id = x.test_id and t.title_uz = v.title and x.question = v.question and x.topic is null;
with t as (insert into public.tests (title_uz, description_uz, subject, kind, grade, time_limit, source, sort_order, is_published)
  values ('DTM mashq: Matematika (2-to‘plam)', 'DTM formatidagi mashq savollari: daraja, tenglama va tengsizliklar, logarifm, trigonometriya, geometriya, ehtimollik, hosila va integral.', 'matematika', 'dtm', null, null, '14-maktab: fan dasturlari va darslik mavzulari asosida sayt uchun tuzilgan mashq savollari (2026, 2-qism). O‘qituvchilar tekshirib, to‘ldirib boradi.', 111, true) returning id)
insert into public.test_questions (test_id, question, options, correct, explanation, topic, difficulty, sort_order) values
  ((select id from t), '2¹⁰ ning qiymatini toping.', array['512', '100', '2048', '1024'], 3, '2¹⁰ = 1024.', 'Daraja va ildiz', 1, 1),
  ((select id from t), '√0,49 = ?', array['0,07', '0,7', '0,49', '7'], 1, '0,7 · 0,7 = 0,49.', 'Daraja va ildiz', 1, 2),
  ((select id from t), '3⁻² = ?', array['1/9', '1/6', '−9', '−6'], 0, 'a⁻ⁿ = 1/aⁿ, 3⁻² = 1/9.', 'Daraja va ildiz', 2, 3),
  ((select id from t), '240 ning 25 foizi nechaga teng?', array['96', '60', '48', '24'], 1, '240 · 0,25 = 60.', 'Foizlar', 1, 4),
  ((select id from t), 'Narx 200 000 so‘m edi. Avval 10 % oshirildi, keyin 10 % kamaytirildi. Yangi narx?', array['200 000 so‘m', '180 000 so‘m', '202 000 so‘m', '198 000 so‘m'], 3, '200 000 · 1,1 = 220 000; 220 000 · 0,9 = 198 000.', 'Foizlar', 3, 5),
  ((select id from t), '5x + 3 = 2x + 18 tenglamani yeching.', array['3', '7', '15', '5'], 3, '3x = 15, x = 5.', 'Tenglamalar', 1, 6),
  ((select id from t), 'x² − 9 = 0 tenglamaning ildizlari?', array['9', '−3 va 3', '3', '−9 va 9'], 1, 'x² = 9, x = ±3.', 'Kvadrat tenglamalar', 1, 7),
  ((select id from t), 'x² + 4x + 4 = 0 tenglamaning ildizi?', array['−4', '−2', '2', '4'], 1, '(x + 2)² = 0, x = −2.', 'Kvadrat tenglamalar', 2, 8),
  ((select id from t), '2x² − 3x − 5 = 0 tenglamaning diskriminantini toping.', array['1', '49', '−31', '31'], 1, 'D = b² − 4ac = 9 + 40 = 49.', 'Kvadrat tenglamalar', 2, 9),
  ((select id from t), 'x + y = 10 va x − y = 4 sistemaning yechimi?', array['x = 3, y = 7', 'x = 6, y = 4', 'x = 7, y = 3', 'x = 5, y = 5'], 2, 'Qo‘shsak: 2x = 14, x = 7; y = 3.', 'Tenglamalar sistemasi', 2, 10),
  ((select id from t), '2x − 3 > 7 tengsizlikni yeching.', array['x < 5', 'x > 5', 'x > 2', 'x > 10'], 1, '2x > 10, x > 5.', 'Tengsizliklar', 1, 11),
  ((select id from t), 'log₃ 81 = ?', array['3', '4', '27', '9'], 1, '3⁴ = 81.', 'Logarifm', 1, 12),
  ((select id from t), 'lg 1000 = ?', array['10', '4', '100', '3'], 3, '10³ = 1000.', 'Logarifm', 1, 13),
  ((select id from t), 'log₂ 32 − log₂ 4 = ?', array['3', '8', '5', '28'], 0, 'log₂ 32 = 5, log₂ 4 = 2, 5 − 2 = 3.', 'Logarifm', 2, 14),
  ((select id from t), 'tg 45° = ?', array['1', '√3', '0', '1/2'], 0, null, 'Trigonometriya', 1, 15),
  ((select id from t), 'sin²α + cos²α = ?', array['tg α', '1', '0', '2'], 1, 'Asosiy trigonometrik ayniyat.', 'Trigonometriya', 1, 16),
  ((select id from t), 'Arifmetik progressiyada a₁ = 5, d = 3. Dastlabki 10 ta hadning yig‘indisi?', array['150', '185', '320', '155'], 1, 'S₁₀ = (2·5 + 9·3) · 10 / 2 = 37 · 5 = 185.', 'Progressiyalar', 3, 17),
  ((select id from t), 'Geometrik progressiyada b₁ = 3, q = 2. Dastlabki 5 ta hadning yig‘indisi?', array['48', '45', '93', '96'], 2, 'S₅ = 3 · (2⁵ − 1) / (2 − 1) = 93.', 'Progressiyalar', 3, 18),
  ((select id from t), 'Asoslari 6 va 10, balandligi 5 bo‘lgan trapetsiyaning yuzi?', array['40', '60', '30', '80'], 0, 'S = (6 + 10) / 2 · 5 = 40.', 'Planimetriya', 2, 19),
  ((select id from t), 'Radiusi 7 ga teng aylananing uzunligi?', array['28π', '49π', '7π', '14π'], 3, 'C = 2πr = 14π.', 'Planimetriya', 1, 20),
  ((select id from t), 'Tomonlari 5, 12 va 13 bo‘lgan uchburchakning yuzi?', array['30', '65', '60', '78'], 0, '5² + 12² = 13² — to‘g‘ri burchakli; S = 5 · 12 / 2 = 30.', 'Planimetriya', 3, 21),
  ((select id from t), 'Oltiburchak ichki burchaklarining yig‘indisi?', array['360°', '540°', '720°', '1080°'], 2, '(n − 2) · 180° = 4 · 180° = 720°.', 'Planimetriya', 2, 22),
  ((select id from t), 'Radiusi 3 ga teng sharning hajmi?', array['27π', '108π', '36π', '12π'], 2, 'V = 4/3 · π · 27 = 36π.', 'Stereometriya', 2, 23),
  ((select id from t), 'O‘yin soqqasi tashlandi. Juft son tushish ehtimoli?', array['1/3', '2/3', '1/2', '1/6'], 2, '6 tadan 3 tasi juft: 2, 4, 6.', 'Ehtimollik', 1, 24),
  ((select id from t), '5 kishidan 2 kishini necha usulda tanlash mumkin?', array['25', '10', '20', '7'], 1, 'C(5, 2) = 5 · 4 / 2 = 10.', 'Kombinatorika', 2, 25),
  ((select id from t), 'y = 3x² − 4x + 1 funksiyaning hosilasi?', array['6x² − 4', '6x + 1', '6x − 4', '3x − 4'], 2, null, 'Hosila', 2, 26),
  ((select id from t), '∫₀² 2x dx = ?', array['1', '8', '2', '4'], 3, 'x² ni 0 dan 2 gacha: 4 − 0 = 4.', 'Integral', 3, 27);
with t as (insert into public.tests (title_uz, description_uz, subject, kind, grade, time_limit, source, sort_order, is_published)
  values ('DTM mashq: Fizika (2-to‘plam)', 'DTM formatidagi mashq savollari: kinematika, dinamika, bosim, ish va energiya, elektr, issiqlik, tebranishlar, optika, atom.', 'fizika', 'dtm', null, null, '14-maktab: fan dasturlari va darslik mavzulari asosida sayt uchun tuzilgan mashq savollari (2026, 2-qism). O‘qituvchilar tekshirib, to‘ldirib boradi.', 112, true) returning id)
insert into public.test_questions (test_id, question, options, correct, explanation, topic, difficulty, sort_order) values
  ((select id from t), '72 km/soat necha m/s ga teng?', array['7,2 m/s', '36 m/s', '72 m/s', '20 m/s'], 3, '72 000 m / 3600 s = 20 m/s.', 'Kinematika', 1, 1),
  ((select id from t), 'Jism tinch holatdan 2 m/s² tezlanish bilan harakatlandi. 5 s dan keyingi tezligi?', array['25 m/s', '2,5 m/s', '7 m/s', '10 m/s'], 3, 'v = at = 2 · 5 = 10 m/s.', 'Kinematika', 1, 2),
  ((select id from t), 'Jism tinch holatdan 2 m/s² tezlanish bilan 5 s harakatlandi. Bosib o‘tgan yo‘li?', array['20 m', '50 m', '25 m', '10 m'], 2, 's = at²/2 = 2 · 25 / 2 = 25 m.', 'Kinematika', 2, 3),
  ((select id from t), 'Erkin tushayotgan jismning 2 s dan keyingi tezligi (g = 10 m/s²)?', array['40 m/s', '10 m/s', '20 m/s', '5 m/s'], 2, 'v = gt = 20 m/s.', 'Kinematika', 1, 4),
  ((select id from t), 'Massasi 5 kg bo‘lgan jismning og‘irligi (g = 10 m/s²)?', array['50 N', '500 N', '0,5 N', '5 N'], 0, 'P = mg = 50 N.', 'Dinamika', 1, 5),
  ((select id from t), 'Bikrligi 200 N/m bo‘lgan prujina 5 sm cho‘zildi. Elastiklik kuchi?', array['1000 N', '10 N', '4 N', '40 N'], 1, 'F = kx = 200 · 0,05 = 10 N.', 'Dinamika', 2, 6),
  ((select id from t), '200 N kuch 0,5 m² yuzaga tik ta’sir qilmoqda. Bosim?', array['200 Pa', '100 Pa', '400 Pa', '1000 Pa'], 2, 'p = F / S = 200 / 0,5 = 400 Pa.', 'Bosim', 1, 7),
  ((select id from t), 'Suvning 10 m chuqurlikdagi bosimi (ρ = 1000 kg/m³, g = 10 m/s², atmosfera bosimisiz)?', array['1000 kPa', '1 kPa', '10 kPa', '100 kPa'], 3, 'p = ρgh = 1000 · 10 · 10 = 100 000 Pa.', 'Bosim', 2, 8),
  ((select id from t), 'Hajmi 0,002 m³ jism suvga to‘liq botirildi. Arximed kuchi (g = 10 m/s²)?', array['20 N', '2 N', '0,2 N', '200 N'], 0, 'F = ρgV = 1000 · 10 · 0,002 = 20 N.', 'Bosim', 2, 9),
  ((select id from t), '50 N kuch jismni kuch yo‘nalishida 4 m ga ko‘chirdi. Bajarilgan ish?', array['12,5 J', '46 J', '54 J', '200 J'], 3, 'A = F · s = 200 J.', 'Ish va quvvat', 1, 10),
  ((select id from t), 'Dvigatel 60 s da 1200 J ish bajardi. Quvvati?', array['1260 W', '2 W', '72 000 W', '20 W'], 3, 'P = A / t = 1200 / 60 = 20 W.', 'Ish va quvvat', 1, 11),
  ((select id from t), 'Massasi 3 kg, tezligi 4 m/s bo‘lgan jismning impulsi?', array['7 kg·m/s', '0,75 kg·m/s', '24 kg·m/s', '12 kg·m/s'], 3, 'p = mv = 12 kg·m/s.', 'Impuls', 1, 12),
  ((select id from t), '4 Om va 6 Om li rezistorlar ketma-ket ulangan. Umumiy qarshilik?', array['10 Om', '2 Om', '2,4 Om', '24 Om'], 0, 'Ketma-ket: R = R₁ + R₂.', 'Elektr toki', 1, 13),
  ((select id from t), '6 Om va 3 Om li rezistorlar parallel ulangan. Umumiy qarshilik?', array['18 Om', '4,5 Om', '9 Om', '2 Om'], 3, 'R = R₁R₂ / (R₁ + R₂) = 18 / 9 = 2 Om.', 'Elektr toki', 2, 14),
  ((select id from t), 'Kuchlanish 220 V, tok kuchi 5 A. Elektr quvvati?', array['44 W', '215 W', '1100 W', '225 W'], 2, 'P = UI = 1100 W.', 'Elektr toki', 1, 15),
  ((select id from t), '1 kW·soat necha joulga teng?', array['3600 J', '3,6·10³ J', '3,6·10⁶ J', '1000 J'], 2, '1000 W · 3600 s = 3 600 000 J.', 'Birliklar', 2, 16),
  ((select id from t), '2 kg suvni 10 °C ga isitish uchun qancha issiqlik kerak (c = 4200 J/(kg·°C))?', array['84 kJ', '840 kJ', '8,4 kJ', '42 kJ'], 0, 'Q = cmΔt = 4200 · 2 · 10 = 84 000 J.', 'Issiqlik', 2, 17),
  ((select id from t), 'Bosim o‘zgarmas bo‘lgan jarayon qanday nomlanadi?', array['Izotermik', 'Izoxorik', 'Adiabatik', 'Izobarik'], 3, null, 'Molekulyar fizika', 1, 18),
  ((select id from t), 'Tebranish chastotasi 50 Hz. Tebranish davri?', array['2 s', '0,5 s', '50 s', '0,02 s'], 3, 'T = 1 / ν = 1 / 50 = 0,02 s.', 'Tebranish va to‘lqinlar', 1, 19),
  ((select id from t), 'Tovush tezligi 340 m/s, chastotasi 170 Hz. To‘lqin uzunligi?', array['57 800 m', '2 m', '0,5 m', '510 m'], 1, 'λ = v / ν = 340 / 170 = 2 m.', 'Tebranish va to‘lqinlar', 2, 20),
  ((select id from t), 'Yassi ko‘zgudagi tasvir qanday bo‘ladi?', array['Mavhum, to‘g‘ri, buyum bilan teng kattalikda', 'Mavhum, teskari, kichraygan', 'Haqiqiy, to‘g‘ri, kattalashgan', 'Haqiqiy, teskari, kichraygan'], 0, null, 'Optika', 1, 21),
  ((select id from t), 'Fokus masofasi 0,5 m bo‘lgan yig‘uvchi linzaning optik kuchi?', array['2 dptr', '5 dptr', '−2 dptr', '0,5 dptr'], 0, 'D = 1 / F = 1 / 0,5 = 2 dptr.', 'Optika', 2, 22),
  ((select id from t), 'Atom yadrosi qanday zarralardan tashkil topgan?', array['Faqat elektronlardan', 'Elektronlar va protonlardan', 'Fotonlardan', 'Protonlar va neytronlardan'], 3, null, 'Atom fizikasi', 1, 23),
  ((select id from t), 'Elektronning zaryadi qanday ishorali?', array['Musbat', 'Manfiy', 'Zaryadsiz', 'Ba’zan musbat, ba’zan manfiy'], 1, null, 'Atom fizikasi', 1, 24),
  ((select id from t), 'Magnit induksiyasining birligi?', array['Veber', 'Gers', 'Tesla', 'Genri'], 2, null, 'Birliklar', 1, 25);
with t as (insert into public.tests (title_uz, description_uz, subject, kind, grade, time_limit, source, sort_order, is_published)
  values ('DTM mashq: Kimyo (2-to‘plam)', 'DTM formatidagi mashq savollari: valentlik va oksidlanish darajasi, molyar massa, eritmalar, reaksiyalar, organik birikmalar.', 'kimyo', 'dtm', null, null, '14-maktab: fan dasturlari va darslik mavzulari asosida sayt uchun tuzilgan mashq savollari (2026, 2-qism). O‘qituvchilar tekshirib, to‘ldirib boradi.', 113, true) returning id)
insert into public.test_questions (test_id, question, options, correct, explanation, topic, difficulty, sort_order) values
  ((select id from t), 'H₂O molekulasida kislorodning valentligi?', array['III', 'II', 'IV', 'I'], 1, null, 'Valentlik', 1, 1),
  ((select id from t), 'H₂SO₄ da oltingugurtning oksidlanish darajasi?', array['−2', '+4', '+6', '+2'], 2, '2·(+1) + x + 4·(−2) = 0, x = +6.', 'Oksidlanish darajasi', 2, 2),
  ((select id from t), 'KMnO₄ da marganesning oksidlanish darajasi?', array['+6', '+4', '+2', '+7'], 3, '+1 + x + 4·(−2) = 0, x = +7.', 'Oksidlanish darajasi', 2, 3),
  ((select id from t), 'Sulfat kislotaning (H₂SO₄) molyar massasi?', array['96 g/mol', '98 g/mol', '100 g/mol', '49 g/mol'], 1, '2·1 + 32 + 4·16 = 98.', 'Mol va molyar massa', 1, 4),
  ((select id from t), 'Natriy gidroksidning (NaOH) molyar massasi?', array['40 g/mol', '23 g/mol', '39 g/mol', '56 g/mol'], 0, '23 + 16 + 1 = 40.', 'Mol va molyar massa', 1, 5),
  ((select id from t), '36 g suv necha mol?', array['1 mol', '0,5 mol', '36 mol', '2 mol'], 3, 'n = m / M = 36 / 18 = 2 mol.', 'Mol va molyar massa', 1, 6),
  ((select id from t), 'Normal sharoitda 11,2 l gaz necha mol?', array['1 mol', '0,25 mol', '0,5 mol', '2 mol'], 2, 'n = V / 22,4 = 0,5 mol.', 'Gazlar', 1, 7),
  ((select id from t), 'Suvda vodorodning massa ulushi taxminan?', array['88,9 %', '11,1 %', '5,6 %', '33,3 %'], 1, '2 / 18 ≈ 0,111.', 'Mol va molyar massa', 2, 8),
  ((select id from t), '180 g suvda 20 g tuz eritildi. Eritmadagi tuzning massa ulushi?', array['10 %', '20 %', '9 %', '11,1 %'], 0, '20 / (180 + 20) = 0,1.', 'Eritmalar', 2, 9),
  ((select id from t), 'Eng elektromanfiy element?', array['Xlor', 'Azot', 'Ftor', 'Kislorod'], 2, null, 'Davriy jadval', 1, 10),
  ((select id from t), 'Ishqoriy metallar davriy jadvalning qaysi guruhida joylashgan?', array['VIII A guruh', 'VII A guruh', 'II A guruh', 'I A guruh'], 3, null, 'Davriy jadval', 1, 11),
  ((select id from t), 'Galogenlar qaysi guruhda joylashgan?', array['VII A guruh', 'I A guruh', 'VIII A guruh', 'VI A guruh'], 0, null, 'Davriy jadval', 1, 12),
  ((select id from t), 'Xlorning tartib raqami?', array['17', '35', '7', '18'], 0, null, 'Davriy jadval', 1, 13),
  ((select id from t), 'Bir elementning izotoplari nimasi bilan farq qiladi?', array['Neytronlar soni bilan', 'Tartib raqami bilan', 'Elektronlar soni bilan', 'Protonlar soni bilan'], 0, null, 'Atom tuzilishi', 2, 14),
  ((select id from t), 'Kislota va asosning o‘zaro ta’siri natijasida nima hosil bo‘ladi?', array['Tuz va suv', 'Kislota va suv', 'Faqat tuz', 'Oksid va vodorod'], 0, 'Bu neytrallanish reaksiyasi.', 'Kimyoviy reaksiyalar', 1, 15),
  ((select id from t), 'Fenolftalein ishqoriy eritmada qanday rangga kiradi?', array['Qizil', 'To‘q pushti (malina)', 'Rangsiz qoladi', 'Sariq'], 1, null, 'Indikatorlar', 1, 16),
  ((select id from t), 'Lakmus kislotali muhitda qanday rangga kiradi?', array['Qizil', 'Binafsha', 'Ko‘k', 'Yashil'], 0, null, 'Indikatorlar', 1, 17),
  ((select id from t), 'Rux xlorid kislota bilan reaksiyaga kirishganda qanday gaz ajraladi?', array['Xlor', 'Karbonat angidrid', 'Kislorod', 'Vodorod'], 3, 'Zn + 2HCl → ZnCl₂ + H₂↑.', 'Kimyoviy reaksiyalar', 1, 18),
  ((select id from t), 'Temir zanglaganda nimalar bilan reaksiyaga kirishadi?', array['Faqat vodorod bilan', 'Argon bilan', 'Kislorod va suv (namlik) bilan', 'Faqat azot bilan'], 2, null, 'Metallar', 2, 19),
  ((select id from t), 'Kalsiy karbonatning formulasi?', array['Ca(OH)₂', 'CaCO₃', 'CaCl₂', 'CaO'], 1, null, 'Formulalar', 1, 20),
  ((select id from t), 'Ozonning formulasi?', array['CO₂', 'O₂', 'H₂O₂', 'O₃'], 3, null, 'Formulalar', 1, 21),
  ((select id from t), 'Etil spirtining formulasi?', array['CH₃COOH', 'C₂H₅OH', 'C₆H₁₂O₆', 'CH₃OH'], 1, null, 'Organik kimyo', 1, 22),
  ((select id from t), 'Glyukozaning formulasi?', array['C₁₂H₂₂O₁₁', 'C₆H₆', 'C₆H₁₂O₆', 'C₂H₅OH'], 2, null, 'Organik kimyo', 1, 23),
  ((select id from t), 'Alkanlarning umumiy formulasi?', array['CₙH₂ₙ₋₂', 'CₙH₂ₙ₊₂', 'CₙH₂ₙ₋₆', 'CₙH₂ₙ'], 1, null, 'Organik kimyo', 2, 24);
with t as (insert into public.tests (title_uz, description_uz, subject, kind, grade, time_limit, source, sort_order, is_published)
  values ('DTM mashq: Biologiya (2-to‘plam)', 'DTM formatidagi mashq savollari: botanika, zoologiya, odam va uning salomatligi, genetika, ekologiya.', 'biologiya', 'dtm', null, null, '14-maktab: fan dasturlari va darslik mavzulari asosida sayt uchun tuzilgan mashq savollari (2026, 2-qism). O‘qituvchilar tekshirib, to‘ldirib boradi.', 114, true) returning id)
insert into public.test_questions (test_id, question, options, correct, explanation, topic, difficulty, sort_order) values
  ((select id from t), 'O‘simlikda suv va mineral moddalarni tuproqdan qaysi organ so‘radi?', array['Meva', 'Gul', 'Barg', 'Ildiz'], 3, null, 'Botanika', 1, 1),
  ((select id from t), 'O‘simliklarga yashil rang beradigan pigment?', array['Xlorofill', 'Melanin', 'Gemoglobin', 'Karotin'], 0, null, 'Botanika', 1, 2),
  ((select id from t), 'Fotosintez natijasida nimalar hosil bo‘ladi?', array['Oqsil va azot', 'Karbonat angidrid va suv', 'Glyukoza va kislorod', 'Faqat suv'], 2, null, 'Botanika', 1, 3),
  ((select id from t), 'Bargdagi ustitsalarning vazifasi?', array['Gaz almashinuvi va suv bug‘lanishi', 'Changlanish', 'Urug‘ hosil qilish', 'Suvni tuproqdan so‘rish'], 0, null, 'Botanika', 2, 4),
  ((select id from t), 'Meva gulning qaysi qismidan rivojlanadi?', array['Changchi', 'Kosacha', 'Gultojibarg', 'Tuguncha'], 3, null, 'Botanika', 2, 5),
  ((select id from t), 'Zamburug‘lar qaysi dunyoga kiradi?', array['Hayvonlar dunyosi', 'Zamburug‘lar dunyosi', 'O‘simliklar dunyosi', 'Bakteriyalar dunyosi'], 1, null, 'Botanika', 1, 6),
  ((select id from t), 'Qushlarning yuragi necha kamerali?', array['2', '3', '5', '4'], 3, null, 'Zoologiya', 1, 7),
  ((select id from t), 'Qaysi hayvon suvda hamda quruqlikda yashovchilarga kiradi?', array['Timsoh', 'Ilon', 'Kaltakesak', 'Baqa'], 3, null, 'Zoologiya', 1, 8),
  ((select id from t), 'Baliqlar nima bilan nafas oladi?', array['O‘pka bilan', 'Jabra bilan', 'Traxeya bilan', 'Teri bilan'], 1, null, 'Zoologiya', 1, 9),
  ((select id from t), 'Ko‘rshapalak qaysi sinfga kiradi?', array['Sudralib yuruvchilar', 'Qushlar', 'Hasharotlar', 'Sutemizuvchilar'], 3, null, 'Zoologiya', 1, 10),
  ((select id from t), 'Odam skeletidagi eng uzun suyak?', array['Son suyagi', 'Katta boldir suyagi', 'Umurtqa', 'Yelka suyagi'], 0, null, 'Odam anatomiyasi', 1, 11),
  ((select id from t), 'Quyosh nuri ta’sirida terida qaysi vitamin hosil bo‘ladi?', array['B₁₂ vitamini', 'C vitamini', 'D vitamini', 'A vitamini'], 2, null, 'Odam salomatligi', 1, 12),
  ((select id from t), 'Singa (tsinga) kasalligi qaysi vitamin yetishmasligidan kelib chiqadi?', array['C vitamini', 'D vitamini', 'A vitamini', 'K vitamini'], 0, null, 'Odam salomatligi', 2, 13),
  ((select id from t), 'Qonni yurakdan a’zolarga olib boradigan tomirlar?', array['Limfa tomirlari', 'Arteriyalar', 'Venalar', 'Nervlar'], 1, null, 'Odam anatomiyasi', 1, 14),
  ((select id from t), 'Ovqat hazm qilish qayerdan boshlanadi?', array['Ingichka ichakdan', 'Oshqozondan', 'Yo‘g‘on ichakdan', 'Og‘iz bo‘shlig‘idan'], 3, null, 'Odam anatomiyasi', 1, 15),
  ((select id from t), 'O‘pkada gaz almashinuvi qayerda sodir bo‘ladi?', array['Bronxlarda', 'Alveolalarda', 'Traxeyada', 'Hiqildoqda'], 1, null, 'Odam anatomiyasi', 2, 16),
  ((select id from t), 'Nerv hujayrasi qanday nomlanadi?', array['Eritrotsit', 'Nefron', 'Neyron', 'Miotsit'], 2, null, 'Odam anatomiyasi', 1, 17),
  ((select id from t), 'DNKning qo‘sh spiral modelini kimlar taklif qilgan?', array['Ch. Darvin va A. Uolles', 'J. Uotson va F. Krik', 'G. Mendel va T. Morgan', 'L. Paster va R. Kox'], 1, null, 'Molekulyar biologiya', 2, 18),
  ((select id from t), 'Aa × aa chatishtirilganda avlodda genotiplar nisbati?', array['3 : 1', '1 : 2 : 1', 'Hammasi Aa', '1 : 1'], 3, 'Avlodning yarmi Aa, yarmi aa.', 'Genetika', 3, 19),
  ((select id from t), 'To‘liq dominantlikda Aa × Aa chatishtirilganda fenotiplar nisbati?', array['1 : 1', '9 : 3 : 3 : 1', '3 : 1', '1 : 2 : 1'], 2, null, 'Genetika', 3, 20),
  ((select id from t), 'Odamning jinsiy hujayralarida (gametalarida) nechta xromosoma bor?', array['46', '23', '22', '44'], 1, null, 'Genetika', 2, 21),
  ((select id from t), 'Penitsillinni kim kashf etgan?', array['Robert Kox', 'Aleksandr Fleming', 'Lui Paster', 'Edvard Jenner'], 1, null, 'Mikrobiologiya', 2, 22),
  ((select id from t), 'Oziq zanjirida produtsentlar (hosil qiluvchilar) kimlar?', array['Yashil o‘simliklar', 'Zamburug‘lar', 'Yirtqich hayvonlar', 'O‘txo‘r hayvonlar'], 0, null, 'Ekologiya', 1, 23),
  ((select id from t), 'Qaysi gaz issiqxona effektining asosiy sabablaridan biri?', array['Karbonat angidrid', 'Geliy', 'Kislorod', 'Azot'], 0, null, 'Ekologiya', 2, 24);
with t as (insert into public.tests (title_uz, description_uz, subject, kind, grade, time_limit, source, sort_order, is_published)
  values ('DTM mashq: Ingliz tili (2-to‘plam)', 'DTM formatidagi mashq savollari: zamonlar, shart gaplar, ko‘chirma gap, modal fe’llar, predloglar va so‘z boyligi.', 'ingliz', 'dtm', null, null, '14-maktab: fan dasturlari va darslik mavzulari asosida sayt uchun tuzilgan mashq savollari (2026, 2-qism). O‘qituvchilar tekshirib, to‘ldirib boradi.', 115, true) returning id)
insert into public.test_questions (test_id, question, options, correct, explanation, topic, difficulty, sort_order) values
  ((select id from t), 'He ___ like coffee.', array['don''t', 'doesn''t', 'isn''t', 'not'], 1, 'He/she/it + does not.', 'Present Simple', 1, 1),
  ((select id from t), 'We ___ to London last year.', array['go', 'went', 'goes', 'have gone'], 1, '«Last year» → Past Simple.', 'Past Simple', 1, 2),
  ((select id from t), 'She has ___ finished her homework.', array['already', 'yet', 'last', 'ago'], 0, '«Already» goes with Present Perfect in positive sentences.', 'Present Perfect', 2, 3),
  ((select id from t), 'While I ___ dinner, the phone rang.', array['have cooked', 'am cooking', 'was cooking', 'cooked'], 2, 'A longer action interrupted → Past Continuous.', 'Past Continuous', 2, 4),
  ((select id from t), 'By next year, they ___ the new bridge.', array['have built', 'built', 'will build', 'will have built'], 3, '«By + future time» → Future Perfect.', 'Future Perfect', 3, 5),
  ((select id from t), 'If I ___ rich, I would travel around the world.', array['were', 'had been', 'will be', 'am'], 0, 'Second conditional: if + Past Simple (were), would + verb.', 'Conditionals', 2, 6),
  ((select id from t), 'He asked me where I ___.', array['lived', 'am living', 'do live', 'live'], 0, 'Reported question: tenses move back, no inversion.', 'Reported speech', 3, 7),
  ((select id from t), 'You ___ smoke here. It''s forbidden.', array['mustn''t', 'can', 'needn''t', 'don''t have to'], 0, 'Prohibition → mustn''t.', 'Modal verbs', 2, 8),
  ((select id from t), 'The book ___ by millions of people every year.', array['is reading', 'read', 'is read', 'reads'], 2, 'Present Simple Passive: is/are + V3.', 'Passive voice', 2, 9),
  ((select id from t), 'I''m interested ___ history.', array['on', 'at', 'for', 'in'], 3, null, 'Prepositions', 1, 10),
  ((select id from t), 'She is good ___ maths.', array['with', 'in', 'on', 'at'], 3, null, 'Prepositions', 1, 11),
  ((select id from t), 'How ___ money do you have?', array['many', 'a lot', 'few', 'much'], 3, 'Money is uncountable → much.', 'Quantifiers', 1, 12),
  ((select id from t), 'I have ___ friends in this city.', array['a few', 'a little', 'much', 'any'], 0, 'Countable plural → a few.', 'Quantifiers', 2, 13),
  ((select id from t), 'Choose the opposite of «cheap».', array['poor', 'expensive', 'easy', 'short'], 1, null, 'Vocabulary', 1, 14),
  ((select id from t), 'Choose the synonym of «begin».', array['start', 'stop', 'finish', 'end'], 0, null, 'Vocabulary', 1, 15),
  ((select id from t), 'Which word is a noun?', array['happy', 'happiness', 'happily', 'unhappy'], 1, null, 'Word formation', 2, 16),
  ((select id from t), 'Choose the plural of «mouse».', array['mices', 'mouse', 'mice', 'mouses'], 2, null, 'Nouns', 1, 17),
  ((select id from t), 'Choose the past form of «buy».', array['bought', 'brought', 'buy', 'buyed'], 0, null, 'Irregular verbs', 1, 18),
  ((select id from t), 'He said, «I am tired.» → He said that he ___ tired.', array['has been', 'is', 'will be', 'was'], 3, null, 'Reported speech', 2, 19),
  ((select id from t), 'She is a teacher, ___?', array['isn''t she', 'wasn''t she', 'doesn''t she', 'is she'], 0, 'Positive sentence → negative tag.', 'Question tags', 2, 20),
  ((select id from t), 'I ___ play football when I was a child, but now I don''t.', array['was used', 'used to', 'am used to', 'use to'], 1, null, 'Used to', 2, 21),
  ((select id from t), 'I enjoy ___ books.', array['read', 'to read', 'reading', 'reads'], 2, '«Enjoy» is followed by -ing.', 'Gerund', 2, 22),
  ((select id from t), 'This test is ___ than the last one.', array['easiest', 'easier', 'easyer', 'more easy'], 1, null, 'Adjectives', 1, 23),
  ((select id from t), 'Neither Tom nor his friends ___ here now.', array['was', 'is', 'be', 'are'], 3, 'The verb agrees with the nearer subject («friends»).', 'Agreement', 3, 24);
with t as (insert into public.tests (title_uz, description_uz, subject, kind, grade, time_limit, source, sort_order, is_published)
  values ('DTM mashq: Ona tili va adabiyot (2-to‘plam)', 'DTM formatidagi mashq savollari: kelishiklar, leksikologiya, yordamchi so‘zlar, gap bo‘laklari, o‘zbek adabiyoti.', 'ona_tili', 'dtm', null, null, '14-maktab: fan dasturlari va darslik mavzulari asosida sayt uchun tuzilgan mashq savollari (2026, 2-qism). O‘qituvchilar tekshirib, to‘ldirib boradi.', 116, true) returning id)
insert into public.test_questions (test_id, question, options, correct, explanation, topic, difficulty, sort_order) values
  ((select id from t), 'O‘zbek tilida nechta kelishik bor?', array['4 ta', '5 ta', '7 ta', '6 ta'], 3, 'Bosh, qaratqich, tushum, jo‘nalish, o‘rin-payt, chiqish.', 'Kelishiklar', 1, 1),
  ((select id from t), 'Tushum kelishigining qo‘shimchasi?', array['-ga', '-dan', '-ni', '-ning'], 2, null, 'Kelishiklar', 1, 2),
  ((select id from t), 'Jo‘nalish kelishigining qo‘shimchasi?', array['-ning', '-da', '-ni', '-ga'], 3, null, 'Kelishiklar', 1, 3),
  ((select id from t), 'Chiqish kelishigining qo‘shimchasi?', array['-da', '-ga', '-dan', '-ni'], 2, null, 'Kelishiklar', 1, 4),
  ((select id from t), 'Ma’nosi qarama-qarshi bo‘lgan so‘zlar qanday ataladi?', array['Omonimlar', 'Antonimlar', 'Paronimlar', 'Sinonimlar'], 1, null, 'Leksikologiya', 1, 5),
  ((select id from t), 'Shakli bir xil, ma’nosi har xil so‘zlar qanday ataladi?', array['Sinonimlar', 'Neologizmlar', 'Antonimlar', 'Omonimlar'], 3, null, 'Leksikologiya', 1, 6),
  ((select id from t), 'Ma’nosi bir-biriga yaqin so‘zlar qanday ataladi?', array['Antonimlar', 'Arxaizmlar', 'Omonimlar', 'Sinonimlar'], 3, null, 'Leksikologiya', 1, 7),
  ((select id from t), '«Faqat», «hatto», «-mi» qaysi so‘z turkumiga kiradi?', array['Undov', 'Bog‘lovchi', 'Ko‘makchi', 'Yuklama'], 3, null, 'Yordamchi so‘zlar', 2, 8),
  ((select id from t), '«Va», «lekin», «ammo» qaysi so‘z turkumiga kiradi?', array['Yuklama', 'Modal so‘z', 'Ko‘makchi', 'Bog‘lovchi'], 3, null, 'Yordamchi so‘zlar', 1, 9),
  ((select id from t), '«Uchun», «bilan», «kabi» qaysi so‘z turkumiga kiradi?', array['Ko‘makchi', 'Yuklama', 'Bog‘lovchi', 'Ravish'], 0, null, 'Yordamchi so‘zlar', 2, 10),
  ((select id from t), '«Albatta», «ehtimol» so‘zlari qaysi turkumga kiradi?', array['Modal so‘z', 'Ravish', 'Undov', 'Sifat'], 0, null, 'Yordamchi so‘zlar', 2, 11),
  ((select id from t), 'To‘ldiruvchi qaysi so‘roqlarga javob beradi?', array['kimni? nimani? kimga? nimaga?', 'kim? nima?', 'qanday? qaysi?', 'qayerda? qachon?'], 0, null, 'Sintaksis', 2, 12),
  ((select id from t), 'Hol qaysi so‘roqlarga javob beradi?', array['kim? nima?', 'kimning? nimaning?', 'qayerda? qachon? qanday?', 'kimni? nimani?'], 2, null, 'Sintaksis', 2, 13),
  ((select id from t), 'Qo‘shma gapning turlari qaysi javobda to‘g‘ri berilgan?', array['Undov va buyruq gaplar', 'Bog‘langan, ergashgan va bog‘lovchisiz qo‘shma gaplar', 'Sodda va yoyiq gaplar', 'Darak va so‘roq gaplar'], 1, null, 'Sintaksis', 3, 14),
  ((select id from t), '«Alpomish» qanday asar?', array['Tarixiy roman', 'Masal', 'O‘zbek xalq dostoni', 'G‘azal'], 2, null, 'Xalq og‘zaki ijodi', 1, 15),
  ((select id from t), '«Sarob» romanining muallifi?', array['Oybek', 'Said Ahmad', 'Abdulla Qahhor', 'Abdulla Qodiriy'], 2, null, 'Adabiyot', 2, 16),
  ((select id from t), '«Shum bola» qissasining muallifi?', array['G‘afur G‘ulom', 'Hamid Olimjon', 'Abdulla Qahhor', 'Erkin Vohidov'], 0, null, 'Adabiyot', 1, 17),
  ((select id from t), '«Navoiy» romanining muallifi?', array['Pirimqul Qodirov', 'Abdulla Qodiriy', 'Oybek', 'Cho‘lpon'], 2, null, 'Adabiyot', 1, 18),
  ((select id from t), '«Mehrobdan chayon» romanining muallifi?', array['Abdulla Qahhor', 'Abdulla Qodiriy', 'Cho‘lpon', 'Oybek'], 1, null, 'Adabiyot', 1, 19),
  ((select id from t), '«Dunyoning ishlari» asarining muallifi?', array['Tog‘ay Murod', 'Said Ahmad', 'O‘tkir Hoshimov', 'Xudoyberdi To‘xtaboyev'], 2, null, 'Adabiyot', 2, 20),
  ((select id from t), '«Sariq devni minib» asarining muallifi?', array['O‘tkir Hoshimov', 'Xudoyberdi To‘xtaboyev', 'Anvar Obidjon', 'G‘afur G‘ulom'], 1, null, 'Adabiyot', 1, 21),
  ((select id from t), 'Pirimqul Qodirovning «Yulduzli tunlar» romani qaysi tarixiy shaxs haqida?', array['Amir Temur', 'Mirzo Ulug‘bek', 'Alisher Navoiy', 'Zahiriddin Muhammad Bobur'], 3, null, 'Adabiyot', 2, 22),
  ((select id from t), '«Devonu lug‘otit turk» asarining muallifi?', array['Mahmud Koshg‘ariy', 'Alisher Navoiy', 'Ahmad Yugnakiy', 'Yusuf Xos Hojib'], 0, null, 'Mumtoz adabiyot', 2, 23),
  ((select id from t), '«Qutadg‘u bilig» dostonining muallifi?', array['Yusuf Xos Hojib', 'Lutfiy', 'Mahmud Koshg‘ariy', 'Ahmad Yassaviy'], 0, null, 'Mumtoz adabiyot', 2, 24),
  ((select id from t), 'Alisher Navoiy «Xamsa»sining birinchi dostoni?', array['«Layli va Majnun»', '«Hayrat ul-abror»', '«Farhod va Shirin»', '«Saddi Iskandariy»'], 1, null, 'Mumtoz adabiyot', 3, 25),
  ((select id from t), '«O‘tkan kunlar» romanining bosh qahramoni?', array['Mirzakarim', 'Otabek', 'Said', 'Anvar'], 1, null, 'Adabiyot', 1, 26),
  ((select id from t), 'Said Ahmadning «Ufq» asari qanday janrda?', array['Trilogiya (roman)', 'G‘azal', 'Masal', 'Doston'], 0, null, 'Adabiyot', 3, 27);
with t as (insert into public.tests (title_uz, description_uz, subject, kind, grade, time_limit, source, sort_order, is_published)
  values ('DTM mashq: O‘zbekiston tarixi (2-to‘plam)', 'DTM formatidagi mashq savollari: qadimgi davr, o‘rta asrlar allomalari, Temuriylar, xonliklar, XX asr va mustaqillik.', 'tarix', 'dtm', null, null, '14-maktab: fan dasturlari va darslik mavzulari asosida sayt uchun tuzilgan mashq savollari (2026, 2-qism). O‘qituvchilar tekshirib, to‘ldirib boradi.', 117, true) returning id)
insert into public.test_questions (test_id, question, options, correct, explanation, topic, difficulty, sort_order) values
  ((select id from t), 'Zardushtiylikning muqaddas kitobi?', array['«Qutadg‘u bilig»', '«Boburnoma»', '«Temur tuzuklari»', '«Avesto»'], 3, null, 'Qadimgi davr', 1, 1),
  ((select id from t), 'Afrosiyob qaysi shaharning qadimiy qismi?', array['Buxoro', 'Samarqand', 'Xiva', 'Termiz'], 1, null, 'Qadimgi davr', 1, 2),
  ((select id from t), 'Kushon podsholigining eng mashhur hukmdori?', array['Muqanna', 'Qutayba', 'Kanishka', 'Spitamen'], 2, null, 'Qadimgi davr', 2, 3),
  ((select id from t), 'Varaxsha saroyi xarobalari qaysi viloyatda joylashgan?', array['Farg‘ona', 'Surxondaryo', 'Xorazm', 'Buxoro'], 3, null, 'Qadimgi davr', 2, 4),
  ((select id from t), '«Movarounnahr» so‘zining ma’nosi?', array['Ikki dengiz oralig‘i', 'Daryoning narigi tomoni', 'Cho‘l va vohalar', 'Tog‘lar o‘lkasi'], 1, null, 'O‘rta asrlar', 2, 5),
  ((select id from t), 'Somoniylar davlatining poytaxti?', array['Urganch', 'Samarqand', 'Marv', 'Buxoro'], 3, null, 'O‘rta asrlar', 2, 6),
  ((select id from t), 'Xorazmshohlar davlatining poytaxti?', array['Xiva', 'Urganch (Gurganj)', 'Samarqand', 'Buxoro'], 1, null, 'O‘rta asrlar', 2, 7),
  ((select id from t), 'Mo‘g‘ullar O‘tror shahrini qaysi yili qamal qila boshlagan?', array['1220-yil', '1405-yil', '1370-yil', '1219-yil'], 3, null, 'Mo‘g‘ullar istilosi', 3, 8),
  ((select id from t), '«Al-Jome’ as-sahih» asarining muallifi?', array['Burhoniddin al-Marg‘inoniy', 'Imom at-Termiziy', 'Abu Mansur al-Moturidiy', 'Imom al-Buxoriy'], 3, null, 'Allomalar', 2, 9),
  ((select id from t), '«Hindiston» asarining muallifi?', array['Muhammad al-Xorazmiy', 'Abu Rayhon Beruniy', 'Mahmud Koshg‘ariy', 'Abu Ali ibn Sino'], 1, null, 'Allomalar', 2, 10),
  ((select id from t), 'Amir Temur qaysi yili vafot etgan?', array['1336-yil', '1405-yil', '1370-yil', '1449-yil'], 1, null, 'Temuriylar davri', 2, 11),
  ((select id from t), '«Temur tuzuklari» kimning nomi bilan bog‘liq?', array['Husayn Boyqaro', 'Zahiriddin Muhammad Bobur', 'Mirzo Ulug‘bek', 'Amir Temur'], 3, null, 'Temuriylar davri', 1, 12),
  ((select id from t), 'Registon maydonidagi uchta madrasadan eng qadimgisi?', array['Ulug‘bek madrasasi', 'Ko‘kaldosh madrasasi', 'Tillakori madrasasi', 'Sherdor madrasasi'], 0, null, 'Temuriylar davri', 3, 13),
  ((select id from t), 'Alisher Navoiy yashagan yillar?', array['1441–1501', '1483–1530', '1394–1449', '1336–1405'], 0, null, 'Temuriylar davri', 2, 14),
  ((select id from t), 'Zahiriddin Muhammad Bobur yashagan yillar?', array['1483–1530', '1500–1550', '1336–1405', '1441–1501'], 0, null, 'Temuriylar davri', 2, 15),
  ((select id from t), 'Temuriylar davrida Hirotda ijod qilgan buyuk miniatyurachi rassom?', array['Kamoliddin Behzod', 'Ural Tansiqboyev', 'Mirak Naqqosh', 'Chingiz Ahmarov'], 0, null, 'Temuriylar davri', 2, 16),
  ((select id from t), 'XVIII–XIX asrlarda hozirgi O‘zbekiston hududidagi uchta davlat?', array['Kushon, Qang‘, Davan', 'Somoniylar, Qoraxoniylar, G‘aznaviylar', 'Oltin O‘rda, Chig‘atoy ulusi, Elxoniylar', 'Buxoro amirligi, Xiva xonligi, Qo‘qon xonligi'], 3, null, 'Xonliklar davri', 1, 17),
  ((select id from t), 'Toshkent Rossiya imperiyasi qo‘shinlari tomonidan qaysi yili bosib olingan?', array['1868-yil', '1876-yil', '1873-yil', '1865-yil'], 3, null, 'Mustamlaka davri', 3, 18),
  ((select id from t), 'Turkiston general-gubernatorligi qaysi yili tuzilgan?', array['1865-yil', '1917-yil', '1924-yil', '1867-yil'], 3, null, 'Mustamlaka davri', 3, 19),
  ((select id from t), '«Padarkush» dramasining muallifi?', array['Abdulla Avloniy', 'Hamza Hakimzoda Niyoziy', 'Munavvar qori', 'Mahmudxo‘ja Behbudiy'], 3, null, 'Jadidchilik', 2, 20),
  ((select id from t), 'O‘zbekiston SSR qaysi yili tuzilgan?', array['1917-yil', '1924-yil', '1936-yil', '1930-yil'], 1, null, 'Sovet davri', 2, 21),
  ((select id from t), '1930-yilgacha O‘zbekiston SSRning poytaxti qaysi shahar edi?', array['Samarqand', 'Buxoro', 'Toshkent', 'Qo‘qon'], 0, null, 'Sovet davri', 3, 22),
  ((select id from t), 'Toshkent zilzilasi qachon sodir bo‘lgan?', array['1966-yil 26-aprel', '1991-yil 31-avgust', '1976-yil 1-sentabr', '1941-yil 22-iyun'], 0, null, 'Sovet davri', 2, 23),
  ((select id from t), 'Ikkinchi jahon urushi qaysi yillarda bo‘lgan?', array['1945–1950', '1941–1943', '1939–1945', '1914–1918'], 2, null, 'Sovet davri', 1, 24),
  ((select id from t), 'O‘zbekiston Respublikasining birinchi Prezidenti?', array['Islom Karimov', 'Shavkat Mirziyoyev', 'Sharof Rashidov', 'Usmon Yusupov'], 0, null, 'Mustaqillik davri', 1, 25),
  ((select id from t), 'O‘zbekiston Respublikasi Davlat bayrog‘i qachon qabul qilingan?', array['1992-yil 2-iyul', '1991-yil 31-avgust', '1992-yil 10-dekabr', '1991-yil 18-noyabr'], 3, null, 'Davlat ramzlari', 3, 26),
  ((select id from t), 'O‘zbekiston Respublikasi Davlat gerbi qachon qabul qilingan?', array['1991-yil 18-noyabr', '1992-yil 8-dekabr', '1993-yil 1-sentabr', '1992-yil 2-iyul'], 3, null, 'Davlat ramzlari', 3, 27),
  ((select id from t), 'O‘zbekiston Respublikasi Davlat madhiyasi qachon qabul qilingan?', array['1994-yil 1-iyul', '1992-yil 10-dekabr', '1992-yil 2-iyul', '1991-yil 18-noyabr'], 1, null, 'Davlat ramzlari', 3, 28);
with t as (insert into public.tests (title_uz, description_uz, subject, kind, grade, time_limit, source, sort_order, is_published)
  values ('DTM mashq: Geografiya (2-to‘plam)', 'DTM formatidagi mashq savollari: O‘zbekiston viloyatlari, chegaralari va suvlari, dunyo geografiyasi, xarita.', 'geografiya', 'dtm', null, null, '14-maktab: fan dasturlari va darslik mavzulari asosida sayt uchun tuzilgan mashq savollari (2026, 2-qism). O‘qituvchilar tekshirib, to‘ldirib boradi.', 118, true) returning id)
insert into public.test_questions (test_id, question, options, correct, explanation, topic, difficulty, sort_order) values
  ((select id from t), 'Qashqadaryo viloyatining markazi?', array['Termiz', 'Qarshi', 'Navoiy', 'Shahrisabz'], 1, null, 'O‘zbekiston ma’muriy tuzilishi', 1, 1),
  ((select id from t), 'Sirdaryo viloyatining markazi?', array['Guliston', 'Yangiyer', 'Sirdaryo', 'Jizzax'], 0, null, 'O‘zbekiston ma’muriy tuzilishi', 2, 2),
  ((select id from t), 'Xorazm viloyatining markazi?', array['Xiva', 'Nukus', 'Xonqa', 'Urganch'], 3, null, 'O‘zbekiston ma’muriy tuzilishi', 1, 3),
  ((select id from t), 'Toshkent viloyatining markazi?', array['Chirchiq', 'Toshkent', 'Nurafshon', 'Angren'], 2, null, 'O‘zbekiston ma’muriy tuzilishi', 3, 4),
  ((select id from t), 'Qoraqalpog‘iston Respublikasining poytaxti?', array['Mo‘ynoq', 'Nukus', 'To‘rtko‘l', 'Urganch'], 1, null, 'O‘zbekiston ma’muriy tuzilishi', 1, 5),
  ((select id from t), 'O‘zbekistonning eng janubiy viloyati?', array['Buxoro', 'Qashqadaryo', 'Surxondaryo', 'Samarqand'], 2, null, 'O‘zbekiston ma’muriy tuzilishi', 1, 6),
  ((select id from t), 'Farg‘ona vodiysida joylashgan viloyatlar?', array['Buxoro, Navoiy, Xorazm', 'Samarqand, Jizzax, Sirdaryo', 'Qashqadaryo, Surxondaryo, Buxoro', 'Andijon, Namangan, Farg‘ona'], 3, null, 'O‘zbekiston ma’muriy tuzilishi', 1, 7),
  ((select id from t), 'O‘zbekistonning maydoni taxminan qancha?', array['1 mln km²', '448,9 ming km²', '2,7 mln km²', '200 ming km²'], 1, null, 'O‘zbekiston hududi', 2, 8),
  ((select id from t), 'O‘zbekiston va Lixtenshteynning umumiy geografik xususiyati?', array['Ikkalasi ham orol davlat', 'Ikkalasi ham Yevropada', 'Ikkalasi ham okean bo‘yida', 'Ikkalasi ham dengizga chiqishi yo‘q davlatlar bilan o‘ralgan'], 3, null, 'O‘zbekiston hududi', 3, 9),
  ((select id from t), 'O‘zbekistonning eng uzun davlat chegarasi qaysi davlat bilan?', array['Afg‘oniston', 'Turkmaniston', 'Qozog‘iston', 'Tojikiston'], 2, null, 'O‘zbekiston chegaralari', 2, 10),
  ((select id from t), 'O‘zbekistonning eng qisqa davlat chegarasi qaysi davlat bilan?', array['Tojikiston', 'Turkmaniston', 'Qirg‘iziston', 'Afg‘oniston'], 3, null, 'O‘zbekiston chegaralari', 2, 11),
  ((select id from t), 'Chorvoq suv ombori qaysi daryoda qurilgan?', array['Zarafshon', 'Qashqadaryo', 'Amudaryo', 'Chirchiq'], 3, null, 'O‘zbekiston suvlari', 2, 12),
  ((select id from t), 'Tuyamo‘yin suv ombori qaysi daryoda?', array['Zarafshon', 'Chirchiq', 'Amudaryo', 'Sirdaryo'], 2, null, 'O‘zbekiston suvlari', 2, 13),
  ((select id from t), 'Aydar–Arnasoy ko‘llar tizimi qaysi viloyatlar hududida?', array['Xorazm va Buxoro', 'Farg‘ona va Namangan', 'Jizzax va Navoiy', 'Surxondaryo va Qashqadaryo'], 2, null, 'O‘zbekiston suvlari', 3, 14),
  ((select id from t), 'Amudaryo qaysi daryolarning qo‘shilishidan hosil bo‘ladi?', array['Panj va Vaxsh', 'Chirchiq va Ohangaron', 'Norin va Qoradaryo', 'Zarafshon va Surxondaryo'], 0, null, 'O‘zbekiston suvlari', 2, 15),
  ((select id from t), 'Sirdaryo qaysi daryolarning qo‘shilishidan hosil bo‘ladi?', array['Norin va Qoradaryo', 'Panj va Vaxsh', 'Sherobod va Surxondaryo', 'Chirchiq va Ohangaron'], 0, null, 'O‘zbekiston suvlari', 2, 16),
  ((select id from t), 'O‘zbekiston qaysi vaqt mintaqasida joylashgan?', array['UTC+4', 'UTC+5', 'UTC+6', 'UTC+3'], 1, null, 'Yer shari', 2, 17),
  ((select id from t), 'Everest (Jomolungma) cho‘qqisining balandligi taxminan?', array['7495 m', '8849 m', '5642 m', '6962 m'], 1, null, 'Dunyo relyefi', 1, 18),
  ((select id from t), 'Dunyo okeanidagi eng chuqur botiq?', array['Mariana botig‘i', 'Tonga botig‘i', 'Puerto-Riko botig‘i', 'Yava botig‘i'], 0, null, 'Dunyo okeani', 1, 19),
  ((select id from t), 'Dunyodagi eng katta issiq cho‘l?', array['Qizilqum', 'Gobi', 'Kalaxari', 'Sahroi Kabir'], 3, null, 'Materiklar', 1, 20),
  ((select id from t), 'Maydoni eng katta davlat?', array['Rossiya', 'AQSh', 'Kanada', 'Xitoy'], 0, null, 'Dunyo davlatlari', 1, 21),
  ((select id from t), 'Eng kichik materik?', array['Janubiy Amerika', 'Yevropa', 'Avstraliya', 'Antarktida'], 2, null, 'Materiklar', 1, 22),
  ((select id from t), 'Dunyodagi eng chuqur ko‘l?', array['Baykal', 'Kaspiy', 'Issiqko‘l', 'Viktoriya'], 0, null, 'Ko‘llar', 2, 23),
  ((select id from t), 'Dunyodagi maydoni eng katta ko‘l?', array['Viktoriya', 'Baykal', 'Yuqori ko‘l', 'Kaspiy dengizi'], 3, null, 'Ko‘llar', 2, 24),
  ((select id from t), 'Ekvator Yer sharini qanday yarimsharlarga ajratadi?', array['Sharqiy va G‘arbiy', 'Shimoliy va Janubiy', 'Kunduzgi va tungi', 'Quruqlik va suv'], 1, null, 'Yer shari', 1, 25),
  ((select id from t), 'Bosh (Grinvich) meridiani Yer sharini qanday yarimsharlarga ajratadi?', array['Materik va okean', 'Issiq va sovuq', 'Shimoliy va Janubiy', 'Sharqiy va G‘arbiy'], 3, null, 'Yer shari', 1, 26),
  ((select id from t), 'Geografik kenglik qanday qiymatlarda o‘lchanadi?', array['0° dan 180° gacha', '−180° dan 180° gacha', '0° dan 90° gacha', '0° dan 360° gacha'], 2, null, 'Xarita', 2, 27),
  ((select id from t), 'Masshtab 1 : 100 000 bo‘lsa, xaritadagi 1 sm joydagi necha km ga teng?', array['100 km', '10 km', '1 km', '0,1 km'], 2, '100 000 sm = 1000 m = 1 km.', 'Xarita', 2, 28);
with t as (insert into public.tests (title_uz, description_uz, subject, kind, grade, time_limit, source, sort_order, is_published)
  values ('DTM mashq: Rus tili (1-to‘plam)', 'Mashq savollari DTM formatida: padejlar, so‘z turkumlari, so‘z tarkibi, imlo, gap bo‘laklari va rus adabiyoti.', 'rus', 'dtm', null, null, '14-maktab: fan dasturlari va darslik mavzulari asosida sayt uchun tuzilgan mashq savollari (2026, 2-qism). O‘qituvchilar tekshirib, to‘ldirib boradi.', 119, true) returning id)
insert into public.test_questions (test_id, question, options, correct, explanation, topic, difficulty, sort_order) values
  ((select id from t), 'Сколько падежей в русском языке?', array['6', '7', '5', '4'], 0, 'Именительный, родительный, дательный, винительный, творительный, предложный.', 'Падежи', 1, 1),
  ((select id from t), 'Какой падеж отвечает на вопросы «кого? чего?»', array['Родительный', 'Винительный', 'Дательный', 'Предложный'], 0, null, 'Падежи', 1, 2),
  ((select id from t), 'Какой падеж отвечает на вопросы «кому? чему?»', array['Дательный', 'Творительный', 'Родительный', 'Именительный'], 0, null, 'Падежи', 1, 3),
  ((select id from t), 'Какой падеж отвечает на вопросы «кем? чем?»', array['Творительный', 'Винительный', 'Дательный', 'Предложный'], 0, null, 'Падежи', 1, 4),
  ((select id from t), 'Какой падеж отвечает на вопросы «о ком? о чём?»', array['Родительный', 'Дательный', 'Творительный', 'Предложный'], 3, null, 'Падежи', 1, 5),
  ((select id from t), 'Какого рода существительное «окно»?', array['Женского', 'Мужского', 'Среднего', 'Общего'], 2, null, 'Существительное', 1, 6),
  ((select id from t), 'Какого рода существительное «кофе»?', array['Среднего', 'Не имеет рода', 'Мужского', 'Женского'], 2, null, 'Существительное', 3, 7),
  ((select id from t), 'Множественное число слова «человек»:', array['люди', 'человеки', 'людей', 'человека'], 0, null, 'Существительное', 1, 8),
  ((select id from t), 'Множественное число слова «ребёнок»:', array['детей', 'дети', 'ребёнки', 'ребята'], 1, null, 'Существительное', 1, 9),
  ((select id from t), 'Антоним к слову «горячий»:', array['тёплый', 'жаркий', 'огненный', 'холодный'], 3, null, 'Лексика', 1, 10),
  ((select id from t), 'Синоним к слову «смелый»:', array['трусливый', 'робкий', 'слабый', 'храбрый'], 3, null, 'Лексика', 1, 11),
  ((select id from t), 'Какой частью речи является слово «быстро»?', array['Существительное', 'Наречие', 'Глагол', 'Прилагательное'], 1, null, 'Части речи', 1, 12),
  ((select id from t), 'Какой частью речи является слово «красивый»?', array['Существительное', 'Причастие', 'Наречие', 'Прилагательное'], 3, null, 'Части речи', 1, 13),
  ((select id from t), 'Какой частью речи является слово «читать»?', array['Глагол', 'Наречие', 'Прилагательное', 'Существительное'], 0, null, 'Части речи', 1, 14),
  ((select id from t), 'Слова «я, ты, он» — это …', array['существительные', 'числительные', 'местоимения', 'союзы'], 2, null, 'Части речи', 1, 15),
  ((select id from t), 'Выберите слово, написанное правильно.', array['шышка', 'жираф', 'жызнь', 'жыраф'], 1, '«Жи», «ши» пишутся с буквой «и».', 'Орфография', 1, 16),
  ((select id from t), 'В каком слове мягкий знак написан правильно?', array['ключь', 'ночь', 'врачь', 'мячь'], 1, 'Мягкий знак после шипящих пишется у существительных женского рода.', 'Орфография', 2, 17),
  ((select id from t), 'Какой глагол совершенного вида?', array['говорить', 'читать', 'написать', 'писать'], 2, 'Совершенный вид отвечает на вопрос «что сделать?».', 'Глагол', 2, 18),
  ((select id from t), 'Прошедшее время глагола «идти» (он):', array['шёл', 'идёт', 'идил', 'шла'], 0, null, 'Глагол', 2, 19),
  ((select id from t), 'Сравнительная степень прилагательного «хороший»:', array['самый хороший', 'хорошо', 'хорошее', 'лучше'], 3, null, 'Прилагательное', 2, 20),
  ((select id from t), 'Превосходная степень прилагательного «большой»:', array['самый большой', 'большее', 'большой-большой', 'больше'], 0, null, 'Прилагательное', 1, 21),
  ((select id from t), 'Я живу ___ Ташкенте.', array['в', 'на', 'из', 'к'], 0, null, 'Предлоги', 1, 22),
  ((select id from t), 'Мы поехали ___ бабушке.', array['на', 'к', 'в', 'у'], 1, null, 'Предлоги', 1, 23),
  ((select id from t), 'Выделите приставку в слове «переход».', array['пере-', 'пе-', '-ход', 'переход'], 0, null, 'Состав слова', 2, 24),
  ((select id from t), 'Выделите корень в слове «лесной».', array['лес', 'лесн', 'лесной', 'ной'], 0, null, 'Состав слова', 2, 25),
  ((select id from t), 'Какой суффикс в слове «домик»?', array['-ок', '-мик', '-ик', '-к'], 2, null, 'Состав слова', 2, 26),
  ((select id from t), 'Главные члены предложения:', array['подлежащее и сказуемое', 'дополнение и определение', 'подлежащее и дополнение', 'обстоятельство и сказуемое'], 0, null, 'Синтаксис', 1, 27),
  ((select id from t), 'Кто написал роман в стихах «Евгений Онегин»?', array['А. С. Пушкин', 'Н. В. Гоголь', 'И. А. Крылов', 'М. Ю. Лермонтов'], 0, null, 'Литература', 1, 28),
  ((select id from t), 'Кто автор романа «Война и мир»?', array['Л. Н. Толстой', 'Ф. М. Достоевский', 'И. С. Тургенев', 'А. П. Чехов'], 0, null, 'Литература', 1, 29),
  ((select id from t), 'Кто автор романа «Преступление и наказание»?', array['М. А. Булгаков', 'Ф. М. Достоевский', 'А. С. Пушкин', 'Л. Н. Толстой'], 1, null, 'Литература', 2, 30),
  ((select id from t), 'Кто написал рассказ «Муму»?', array['И. С. Тургенев', 'А. П. Чехов', 'Л. Н. Толстой', 'Н. В. Гоголь'], 0, null, 'Литература', 2, 31);
with t as (insert into public.tests (title_uz, description_uz, subject, kind, grade, time_limit, source, sort_order, is_published)
  values ('DTM mashq: Informatika (1-to‘plam)', 'Mashq savollari DTM formatida: axborot birliklari, sanoq sistemalari, mantiq, kompyuter qurilmalari, internet, Excel, Python asoslari.', 'informatika', 'dtm', null, null, '14-maktab: fan dasturlari va darslik mavzulari asosida sayt uchun tuzilgan mashq savollari (2026, 2-qism). O‘qituvchilar tekshirib, to‘ldirib boradi.', 120, true) returning id)
insert into public.test_questions (test_id, question, options, correct, explanation, topic, difficulty, sort_order) values
  ((select id from t), '1 bayt necha bitga teng?', array['16', '10', '1024', '8'], 3, null, 'Axborot birliklari', 1, 1),
  ((select id from t), '1 Kbayt necha baytga teng?', array['512', '1000', '1024', '8'], 2, null, 'Axborot birliklari', 1, 2),
  ((select id from t), '1 Mbayt necha Kbaytga teng?', array['1000', '8', '100', '1024'], 3, null, 'Axborot birliklari', 1, 3),
  ((select id from t), 'Ikkilik sanoq sistemasidagi 1010₂ soni o‘nlikda nechaga teng?', array['1010', '10', '5', '12'], 1, '8 + 0 + 2 + 0 = 10.', 'Sanoq sistemalari', 2, 4),
  ((select id from t), '13 sonini ikkilik sanoq sistemasida yozing.', array['1011', '1101', '1110', '1001'], 1, '13 = 8 + 4 + 1.', 'Sanoq sistemalari', 2, 5),
  ((select id from t), '111₂ + 1₂ = ?', array['112₂', '1001₂', '1000₂', '1110₂'], 2, '7 + 1 = 8 = 1000₂.', 'Sanoq sistemalari', 2, 6),
  ((select id from t), 'O‘n oltilik sanoq sistemasidagi F raqami o‘nlikda nechaga teng?', array['15', '16', '14', '6'], 0, null, 'Sanoq sistemalari', 1, 7),
  ((select id from t), 'Sakkizlik sanoq sistemasidagi 17₈ o‘nlikda nechaga teng?', array['15', '8', '71', '17'], 0, '1·8 + 7 = 15.', 'Sanoq sistemalari', 2, 8),
  ((select id from t), 'Mantiqiy «VA» (AND) amali: 1 VA 0 = ?', array['10', '2', '1', '0'], 3, 'VA faqat ikkalasi ham 1 bo‘lsa 1 beradi.', 'Mantiq', 1, 9),
  ((select id from t), 'Mantiqiy «YOKI» (OR) amali: 1 YOKI 0 = ?', array['2', '10', '1', '0'], 2, null, 'Mantiq', 1, 10),
  ((select id from t), 'Mantiqiy «EMAS» (NOT) amali: EMAS 1 = ?', array['2', '0', '1', '−1'], 1, null, 'Mantiq', 1, 11),
  ((select id from t), 'Kompyuterning ma’lumotlarni qayta ishlovchi asosiy qurilmasi?', array['Printer', 'Klaviatura', 'Markaziy protsessor', 'Monitor'], 2, null, 'Kompyuter qurilmalari', 1, 12),
  ((select id from t), 'Elektr toki o‘chganda ma’lumotlari o‘chib ketadigan xotira?', array['Operativ xotira (RAM)', 'Optik disk', 'Fleshka', 'Qattiq disk'], 0, null, 'Kompyuter qurilmalari', 1, 13),
  ((select id from t), 'Qaysi biri kiritish qurilmasi?', array['Printer', 'Monitor', 'Klaviatura', 'Karnay'], 2, null, 'Kompyuter qurilmalari', 1, 14),
  ((select id from t), 'Qaysi biri chiqarish qurilmasi?', array['Mikrofon', 'Sichqoncha', 'Skaner', 'Printer'], 3, null, 'Kompyuter qurilmalari', 1, 15),
  ((select id from t), 'Qaysi biri operatsion tizim?', array['Windows', 'Microsoft Word', 'Excel', 'Google Chrome'], 0, null, 'Dasturiy ta’minot', 1, 16),
  ((select id from t), 'Qaysi biri brauzer?', array['Google Chrome', 'Paint', 'Telegram Desktop', 'Windows'], 0, null, 'Internet', 1, 17),
  ((select id from t), 'Veb-sahifalar qaysi til yordamida yaratiladi?', array['HTML', 'Excel', 'SQL', 'Paint'], 0, null, 'Internet', 1, 18),
  ((select id from t), '«https» manzilidagi «s» harfi nimani bildiradi?', array['Server nomini', 'Xavfsiz (shifrlangan) ulanishni', 'Sahifa sonini', 'Saytning sekinligini'], 1, null, 'Internet', 2, 19),
  ((select id from t), 'IP-manzil nima?', array['Fayl nomi', 'Elektron pochta paroli', 'Dastur nomi', 'Tarmoqdagi qurilmaning raqamli manzili'], 3, null, 'Internet', 2, 20),
  ((select id from t), 'Excel’da formula qaysi belgi bilan boshlanadi?', array['#', '@', '+', '='], 3, null, 'Elektron jadvallar', 1, 21),
  ((select id from t), 'Excel’da A1 = 2, A2 = 3, A3 = 5 bo‘lsa, =SUM(A1:A3) natijasi?', array['5', '3', '30', '10'], 3, '2 + 3 + 5 = 10.', 'Elektron jadvallar', 1, 22),
  ((select id from t), 'Excel’da B ustun va 4-qator kesishgan katak manzili?', array['4B', 'B4', 'B:4', 'D2'], 1, null, 'Elektron jadvallar', 1, 23),
  ((select id from t), 'Python: print(2 ** 3) natijasi?', array['5', '6', '8', '23'], 2, '** — darajaga ko‘tarish.', 'Python', 1, 24),
  ((select id from t), 'Python: print(7 // 2) natijasi?', array['3', '4', '1', '3.5'], 0, '// — butun bo‘lish.', 'Python', 2, 25),
  ((select id from t), 'Python: print(7 % 3) natijasi?', array['2.33', '2', '1', '0'], 2, '% — bo‘lishdan qoldiq.', 'Python', 2, 26),
  ((select id from t), 'Python: len("maktab") natijasi?', array['1', '5', '7', '6'], 3, null, 'Python', 1, 27),
  ((select id from t), 'Algoritm nima?', array['Faylning nomi', 'Kompyuterning qismi', 'Masalani yechish uchun aniq ko‘rsatmalar ketma-ketligi', 'Dasturlash tili'], 2, null, 'Algoritmlar', 1, 28),
  ((select id from t), 'Blok-sxemada romb shakli nimani bildiradi?', array['Ma’lumot kiritish', 'Shart (tarmoqlanish)', 'Boshlanish va tugash', 'Hisoblash amali'], 1, null, 'Algoritmlar', 2, 29),
  ((select id from t), '«.docx» kengaytmali fayl qaysi dasturga tegishli?', array['PowerPoint', 'Microsoft Word', 'Paint', 'Microsoft Excel'], 1, null, 'Dasturiy ta’minot', 1, 30),
  ((select id from t), 'Ctrl + C tugmalari nima qiladi?', array['Kesib oladi', 'Saqlaydi', 'Joylashtiradi', 'Nusxa oladi'], 3, null, 'Dasturiy ta’minot', 1, 31),
  ((select id from t), 'Ctrl + V tugmalari nima qiladi?', array['O‘chiradi', 'Chop etadi', 'Joylashtiradi', 'Nusxa oladi'], 2, null, 'Dasturiy ta’minot', 1, 32);
with t as (insert into public.tests (title_uz, description_uz, subject, kind, grade, time_limit, source, sort_order, is_published)
  values ('DTM mashq: Huquq asoslari (1-to‘plam)', 'Mashq savollari: O‘zbekiston Respublikasi Konstitutsiyasi, davlat hokimiyati, davlat ramzlari, inson huquqlari va huquq asoslari.', 'huquq', 'dtm', null, null, '14-maktab: fan dasturlari va darslik mavzulari asosida sayt uchun tuzilgan mashq savollari (2026, 2-qism). O‘qituvchilar tekshirib, to‘ldirib boradi.', 121, true) returning id)
insert into public.test_questions (test_id, question, options, correct, explanation, topic, difficulty, sort_order) values
  ((select id from t), 'O‘zbekistonda Konstitutsiya kuni qachon nishonlanadi?', array['30-aprel', '10-dekabr', '8-dekabr', '1-sentabr'], 2, null, 'Konstitutsiya', 1, 1),
  ((select id from t), 'O‘zbekiston Respublikasining amaldagi Konstitutsiyasi (yangi tahriri) qanday qabul qilingan?', array['2017-yil 1-yanvarda farmon bilan', '2016-yil 4-dekabrda saylovda', '1992-yil 8-dekabrda Oliy Kengash sessiyasida', '2023-yil 30-aprelda referendumda'], 3, null, 'Konstitutsiya', 2, 2),
  ((select id from t), 'Oliy yuridik kuchga ega bo‘lgan hujjat?', array['Hukumat qarori', 'Prezident farmoni', 'Mahalliy hokim qarori', 'Konstitutsiya'], 3, null, 'Konstitutsiya', 1, 3),
  ((select id from t), 'Oliy Majlis qanday palatalardan iborat?', array['Oliy sud va Konstitutsiyaviy sud', 'Qonunchilik palatasi va Senat', 'Faqat Qonunchilik palatasi', 'Senat va Vazirlar Mahkamasi'], 1, null, 'Davlat hokimiyati', 1, 4),
  ((select id from t), 'Oliy Majlis Qonunchilik palatasi nechta deputatdan iborat?', array['65', '100', '150', '120'], 2, null, 'Davlat hokimiyati', 2, 5),
  ((select id from t), 'Amaldagi Konstitutsiyaga ko‘ra Prezident necha yil muddatga saylanadi?', array['5 yil', '7 yil', '6 yil', '4 yil'], 1, null, 'Davlat hokimiyati', 2, 6),
  ((select id from t), 'Prezidentlikka nomzod kamida necha yoshda bo‘lishi kerak?', array['35', '25', '40', '30'], 0, null, 'Davlat hokimiyati', 2, 7),
  ((select id from t), 'Fuqarolar necha yoshdan saylashda ishtirok etish huquqiga ega?', array['25', '18', '21', '16'], 1, null, 'Saylov huquqi', 1, 8),
  ((select id from t), 'O‘zbekiston Respublikasining davlat tili?', array['O‘zbek tili', 'Qoraqalpoq tili', 'Ingliz tili', 'Rus tili'], 0, null, 'Konstitutsiya', 1, 9),
  ((select id from t), 'O‘zbekiston Respublikasining poytaxti?', array['Nukus', 'Toshkent', 'Samarqand', 'Buxoro'], 1, null, 'Konstitutsiya', 1, 10),
  ((select id from t), 'Qoraqalpog‘iston Respublikasining poytaxti?', array['Beruniy', 'Nukus', 'Urganch', 'Mo‘ynoq'], 1, null, 'Konstitutsiya', 1, 11),
  ((select id from t), 'Davlat hokimiyati qaysi tarmoqlarga bo‘linadi?', array['Qonun chiqaruvchi, ijro etuvchi va sud', 'Iqtisodiy va siyosiy', 'Harbiy va fuqarolik', 'Markaziy va mahalliy'], 0, null, 'Davlat hokimiyati', 1, 12),
  ((select id from t), 'Ijro etuvchi hokimiyatni amalga oshiruvchi hukumat?', array['Oliy sud', 'Senat', 'Vazirlar Mahkamasi', 'Qonunchilik palatasi'], 2, null, 'Davlat hokimiyati', 2, 13),
  ((select id from t), 'O‘zbekiston Respublikasida davlat boshlig‘i kim?', array['Bosh vazir', 'Prezident', 'Oliy sud raisi', 'Senat raisi'], 1, null, 'Davlat hokimiyati', 1, 14),
  ((select id from t), 'Qonunlarning Konstitutsiyaga muvofiqligini qaysi organ tekshiradi?', array['Vazirlar Mahkamasi', 'Konstitutsiyaviy sud', 'Oliy sud', 'Bosh prokuratura'], 1, null, 'Sud hokimiyati', 2, 15),
  ((select id from t), 'O‘zbekiston Respublikasining davlat ramzlari?', array['Bayroq va pasport', 'Bayroq, gerb va madhiya', 'Gerb va Konstitutsiya', 'Madhiya va so‘m'], 1, null, 'Davlat ramzlari', 1, 16),
  ((select id from t), 'O‘zbekiston Davlat bayrog‘ida nechta yulduz bor?', array['12', '7', '10', '14'], 0, null, 'Davlat ramzlari', 1, 17),
  ((select id from t), 'O‘zbekiston Davlat gerbidagi afsonaviy qush?', array['Burgut', 'Humo', 'Laylak', 'Qaldirg‘och'], 1, null, 'Davlat ramzlari', 1, 18),
  ((select id from t), 'O‘zbekistonda Mustaqillik kuni qachon nishonlanadi?', array['9-may', '8-dekabr', '1-sentabr', '21-mart'], 2, null, 'Davlat bayramlari', 1, 19),
  ((select id from t), 'O‘zbekiston Respublikasi davlat boshqaruvi shakliga ko‘ra qanday davlat?', array['Monarxiya', 'Respublika', 'Konfederatsiya', 'Federatsiya'], 1, null, 'Davlat asoslari', 2, 20),
  ((select id from t), 'Inson huquqlari umumjahon deklaratsiyasi qachon qabul qilingan?', array['1989-yil 20-noyabr', '1945-yil 24-oktabr', '1948-yil 10-dekabr', '1992-yil 8-dekabr'], 2, null, 'Inson huquqlari', 2, 21),
  ((select id from t), 'Birlashgan Millatlar Tashkiloti qaysi yili tashkil topgan?', array['1948-yil', '1945-yil', '1991-yil', '1918-yil'], 1, null, 'Xalqaro huquq', 1, 22),
  ((select id from t), 'Bola huquqlari to‘g‘risidagi konvensiya qaysi yili qabul qilingan?', array['1948-yil', '1989-yil', '2001-yil', '1995-yil'], 1, null, 'Inson huquqlari', 2, 23),
  ((select id from t), 'O‘zbekistonda nikoh yoshi (erkak va ayol uchun) necha yosh?', array['20', '18', '17', '16'], 1, null, 'Oila huquqi', 2, 24),
  ((select id from t), 'Fuqaro to‘liq muomala layoqatiga (voyaga yetgach) necha yoshdan ega bo‘ladi?', array['14', '21', '16', '18'], 3, null, 'Fuqarolik huquqi', 2, 25),
  ((select id from t), 'Oliy Majlisning Inson huquqlari bo‘yicha vakili qanday nomlanadi?', array['Notarius', 'Advokat', 'Prokuror', 'Ombudsman'], 3, null, 'Inson huquqlari', 2, 26),
  ((select id from t), 'Huquq normasi nima?', array['Faqat tashkilot ichida amal qiladigan ichki tartib qoidasi', 'Oilada avloddan avlodga o‘tib keladigan an’ana va urf-odat', 'Jamiyatda shakllangan, bajarilishi ixtiyoriy bo‘lgan axloqiy tavsiya', 'Davlat tomonidan o‘rnatiladigan va ta’minlanadigan umummajburiy xulq-atvor qoidasi'], 3, null, 'Huquq nazariyasi', 2, 27),
  ((select id from t), 'Jinoyat nima?', array['Jamoat joyida odob-axloq qoidalariga rioya qilmaslik', 'Mehnat intizomini buzish, uning uchun faqat hayfsan beriladi', 'Jinoyat kodeksida taqiqlangan, jazo qo‘llash tahdidi bilan man etilgan aybli ijtimoiy xavfli qilmish', 'Shartnoma majburiyatini o‘z vaqtida bajarmaslik'], 2, null, 'Jinoyat huquqi', 3, 28),
  ((select id from t), 'Referendum nima?', array['Muhim masalalar bo‘yicha umumxalq ovoz berishi', 'Parlament majlisi', 'Hukumat qarori', 'Sud jarayoni'], 0, null, 'Davlat asoslari', 1, 29),
  ((select id from t), 'Mahalla qanday organ?', array['Harbiy qism', 'Sud organi', 'Fuqarolarning o‘zini o‘zi boshqarish organi', 'Vazirlik'], 2, null, 'Davlat asoslari', 1, 30),
  ((select id from t), 'Konstitutsiyaga ko‘ra umumiy o‘rta ta’lim qanday?', array['Faqat shaharlarda', 'Majburiy; davlat ta’lim muassasalarida bepul', 'Faqat 18 yoshdan keyin', 'Ixtiyoriy va pullik'], 1, null, 'Inson huquqlari', 2, 31);
with t as (insert into public.tests (title_uz, description_uz, subject, kind, grade, time_limit, source, sort_order, is_published)
  values ('Matematika | 5-sinf: natural sonlar va kasrlar', '5-sinf matematika mavzulari: natural sonlar ustida amallar, bo‘linish belgilari, oddiy va o‘nli kasrlar, perimetr va yuza, o‘lchov birliklari.', 'matematika', 'mavzu', 5, 20, '14-maktab: fan dasturlari va darslik mavzulari asosida sayt uchun tuzilgan mashq savollari (2026, 2-qism). O‘qituvchilar tekshirib, to‘ldirib boradi.', 21, true) returning id)
insert into public.test_questions (test_id, question, options, correct, explanation, topic, difficulty, sort_order) values
  ((select id from t), '1256 + 744 = ?', array['1900', '2000', '1990', '2100'], 1, null, 'Natural sonlar', 1, 1),
  ((select id from t), '1000 − 387 = ?', array['713', '687', '623', '613'], 3, null, 'Natural sonlar', 1, 2),
  ((select id from t), '125 · 8 = ?', array['1025', '1000', '800', '1250'], 1, null, 'Natural sonlar', 1, 3),
  ((select id from t), '144 : 12 = ?', array['13', '12', '11', '14'], 1, null, 'Natural sonlar', 1, 4),
  ((select id from t), '9² = ?', array['81', '72', '99', '18'], 0, '9 · 9 = 81.', 'Natural sonlar', 1, 5),
  ((select id from t), 'x + 35 = 80 tenglamani yeching.', array['45', '35', '55', '115'], 0, 'x = 80 − 35 = 45.', 'Tenglamalar', 1, 6),
  ((select id from t), '3687 sonini yuzlargacha yaxlitlang.', array['4000', '3600', '3700', '3690'], 2, null, 'Natural sonlar', 2, 7),
  ((select id from t), 'Qaysi son 3 ga qoldiqsiz bo‘linadi?', array['124', '125', '127', '123'], 3, 'Raqamlar yig‘indisi 1 + 2 + 3 = 6 — 3 ga bo‘linadi.', 'Bo‘linish belgilari', 2, 8),
  ((select id from t), 'Qaysi son 5 ga qoldiqsiz bo‘linadi?', array['529', '251', '243', '245'], 3, '0 yoki 5 bilan tugagan sonlar 5 ga bo‘linadi.', 'Bo‘linish belgilari', 1, 9),
  ((select id from t), '3/5 + 1/5 = ?', array['3/25', '2/5', '4/5', '4/10'], 2, null, 'Oddiy kasrlar', 1, 10),
  ((select id from t), '7/8 − 3/8 = ?', array['1/2', '4/16', '10/8', '1/4'], 0, '4/8 = 1/2.', 'Oddiy kasrlar', 2, 11),
  ((select id from t), '2 1/3 aralash sonni noto‘g‘ri kasr shaklida yozing.', array['7/3', '5/3', '3/7', '6/3'], 0, '2 · 3 + 1 = 7.', 'Oddiy kasrlar', 2, 12),
  ((select id from t), '0,5 + 0,25 = ?', array['7,5', '0,30', '0,75', '0,525'], 2, null, 'O‘nli kasrlar', 1, 13),
  ((select id from t), '4,2 · 10 = ?', array['42', '420', '4,20', '0,42'], 0, '10 ga ko‘paytirilganda vergul bir xona o‘ngga suriladi.', 'O‘nli kasrlar', 1, 14),
  ((select id from t), 'Bo‘yi 8 sm, eni 5 sm bo‘lgan to‘g‘ri to‘rtburchakning perimetri?', array['26 sm', '40 sm', '13 sm', '80 sm'], 0, 'P = 2 · (8 + 5) = 26 sm.', 'Perimetr va yuza', 1, 15),
  ((select id from t), 'Bo‘yi 8 sm, eni 5 sm bo‘lgan to‘g‘ri to‘rtburchakning yuzi?', array['26 sm²', '13 sm²', '45 sm²', '40 sm²'], 3, 'S = 8 · 5 = 40 sm².', 'Perimetr va yuza', 1, 16),
  ((select id from t), '2,5 soat necha daqiqa?', array['125 daqiqa', '150 daqiqa', '90 daqiqa', '250 daqiqa'], 1, '2,5 · 60 = 150.', 'O‘lchov birliklari', 2, 17),
  ((select id from t), '3 km 250 m necha metr?', array['325 m', '3250 m', '3025 m', '32 500 m'], 1, null, 'O‘lchov birliklari', 1, 18),
  ((select id from t), '24 ta daftar 3 o‘quvchiga teng bo‘lindi. Har biriga nechtadan tegdi?', array['21 ta', '8 ta', '7 ta', '6 ta'], 1, null, 'Masalalar', 1, 19),
  ((select id from t), 'To‘g‘ri burchak necha gradus?', array['45°', '90°', '60°', '180°'], 1, null, 'Burchaklar', 1, 20);
with t as (insert into public.tests (title_uz, description_uz, subject, kind, grade, time_limit, source, sort_order, is_published)
  values ('Algebra | 8-sinf: ildizlar va kvadrat tenglamalar', '8-sinf algebra mavzulari: kvadrat ildiz, darajalar, ko‘paytuvchilarga ajratish, kvadrat tenglamalar va Viyet teoremasi, tengsizliklar.', 'matematika', 'mavzu', 8, 25, '14-maktab: fan dasturlari va darslik mavzulari asosida sayt uchun tuzilgan mashq savollari (2026, 2-qism). O‘qituvchilar tekshirib, to‘ldirib boradi.', 22, true) returning id)
insert into public.test_questions (test_id, question, options, correct, explanation, topic, difficulty, sort_order) values
  ((select id from t), '√81 = ?', array['8', '81', '40,5', '9'], 3, null, 'Kvadrat ildiz', 1, 1),
  ((select id from t), '√2 · √8 = ?', array['4', '2√2', '√10', '16'], 0, '√16 = 4.', 'Kvadrat ildiz', 2, 2),
  ((select id from t), '(√5)² = ?', array['√5', '10', '25', '5'], 3, null, 'Kvadrat ildiz', 1, 3),
  ((select id from t), '1/√2 ni maxrajini irratsionallikdan qutqarib yozing.', array['√2/2', '2/√2', '√2', '1/2'], 0, '1/√2 = √2/(√2·√2) = √2/2.', 'Kvadrat ildiz', 3, 4),
  ((select id from t), '√(3² + 4²) = ?', array['7', '12', '25', '5'], 3, '√25 = 5.', 'Kvadrat ildiz', 1, 5),
  ((select id from t), 'a² · a³ = ?', array['a', '2a⁵', 'a⁵', 'a⁶'], 2, null, 'Darajalar', 1, 6),
  ((select id from t), '(a³)² = ?', array['2a³', 'a⁵', 'a⁶', 'a⁹'], 2, null, 'Darajalar', 1, 7),
  ((select id from t), '2⁻³ = ?', array['−8', '−6', '1/8', '1/6'], 2, null, 'Darajalar', 2, 8),
  ((select id from t), '0,00052 sonining standart shakli?', array['5,2 · 10⁻⁴', '5,2 · 10⁴', '52 · 10⁻⁵', '0,52 · 10⁻³'], 0, null, 'Darajalar', 2, 9),
  ((select id from t), 'x² − 16 ni ko‘paytuvchilarga ajrating.', array['(x − 8)(x + 2)', '(x − 4)²', '(x + 4)²', '(x − 4)(x + 4)'], 3, 'a² − b² = (a − b)(a + b).', 'Ko‘paytuvchilarga ajratish', 1, 10),
  ((select id from t), '(x² − 1) / (x − 1) ni soddalashtiring (x ≠ 1).', array['x − 1', '1', 'x + 1', 'x'], 2, 'x² − 1 = (x − 1)(x + 1).', 'Ko‘paytuvchilarga ajratish', 2, 11),
  ((select id from t), 'x² = 49 tenglamaning ildizlari?', array['−7', '49', '7', '−7 va 7'], 3, null, 'Kvadrat tenglamalar', 1, 12),
  ((select id from t), 'x² − 6x + 5 = 0 tenglamaning ildizlari?', array['1 va 5', '−1 va −5', '2 va 3', '1 va 6'], 0, 'Yig‘indi 6, ko‘paytma 5.', 'Kvadrat tenglamalar', 2, 13),
  ((select id from t), 'x² + 2x − 3 = 0 tenglamaning diskriminanti?', array['8', '4', '16', '−8'], 2, 'D = 4 + 12 = 16.', 'Kvadrat tenglamalar', 2, 14),
  ((select id from t), 'x² − 7x + 10 = 0 tenglama ildizlarining yig‘indisi?', array['10', '−7', '7', '−10'], 2, 'Viyet teoremasi: x₁ + x₂ = −b/a = 7.', 'Viyet teoremasi', 2, 15),
  ((select id from t), 'x² + 3x − 10 = 0 tenglama ildizlarining ko‘paytmasi?', array['−10', '−3', '10', '3'], 0, 'Viyet teoremasi: x₁ · x₂ = c/a = −10.', 'Viyet teoremasi', 2, 16),
  ((select id from t), '−3x < 12 tengsizlikni yeching.', array['x > −4', 'x < 4', 'x < −4', 'x > 4'], 0, 'Manfiy songa bo‘lganda tengsizlik belgisi o‘zgaradi.', 'Tengsizliklar', 3, 17),
  ((select id from t), '2x + y = 7 va x − y = 2 sistemaning yechimi?', array['x = 4, y = −1', 'x = 1, y = 5', 'x = 2, y = 3', 'x = 3, y = 1'], 3, 'Qo‘shsak: 3x = 9, x = 3; y = 1.', 'Tenglamalar sistemasi', 2, 18),
  ((select id from t), 'y = 1/x funksiyaning grafigi qanday nomlanadi?', array['Giperbola', 'To‘g‘ri chiziq', 'Parabola', 'Aylana'], 0, null, 'Funksiyalar', 1, 19),
  ((select id from t), 'y = x² parabolaning uchi qaysi nuqtada?', array['(0; 0)', '(1; 1)', '(1; 0)', '(0; 1)'], 0, null, 'Funksiyalar', 1, 20);
with t as (insert into public.tests (title_uz, description_uz, subject, kind, grade, time_limit, source, sort_order, is_published)
  values ('Geometriya | 7–9-sinf: uchburchak, to‘rtburchak, aylana', '7–9-sinf geometriya mavzulari: burchaklar, uchburchaklar, Pifagor teoremasi, to‘rtburchaklar yuzi, aylana va doira.', 'matematika', 'mavzu', 9, 20, '14-maktab: fan dasturlari va darslik mavzulari asosida sayt uchun tuzilgan mashq savollari (2026, 2-qism). O‘qituvchilar tekshirib, to‘ldirib boradi.', 23, true) returning id)
insert into public.test_questions (test_id, question, options, correct, explanation, topic, difficulty, sort_order) values
  ((select id from t), 'Qo‘shni burchaklardan biri 65°. Ikkinchisi necha gradus?', array['25°', '115°', '135°', '65°'], 1, 'Qo‘shni burchaklar yig‘indisi 180°.', 'Burchaklar', 1, 1),
  ((select id from t), 'Vertikal burchaklar haqida qaysi fikr to‘g‘ri?', array['Biri ikkinchisidan ikki marta katta', 'Yig‘indisi 180°', 'Ular teng', 'Yig‘indisi 90°'], 2, null, 'Burchaklar', 1, 2),
  ((select id from t), 'Teng tomonli uchburchakning har bir burchagi?', array['90°', '120°', '45°', '60°'], 3, null, 'Uchburchaklar', 1, 3),
  ((select id from t), 'Teng yonli uchburchakning asosidagi burchaklari haqida to‘g‘ri fikr?', array['Ular teng', 'Biri o‘tmas', 'Ular har doim 90°', 'Yig‘indisi 90°'], 0, null, 'Uchburchaklar', 1, 4),
  ((select id from t), 'Uchburchakning tashqi burchagi nimaga teng?', array['180° ga', 'Qo‘shni ichki burchakka', 'Uchala ichki burchak yig‘indisiga', 'U bilan qo‘shni bo‘lmagan ikki ichki burchak yig‘indisiga'], 3, null, 'Uchburchaklar', 2, 5),
  ((select id from t), 'Katetlari 9 va 12 bo‘lgan to‘g‘ri burchakli uchburchakning gipotenuzasi?', array['108', '21', '13', '15'], 3, '√(81 + 144) = √225 = 15.', 'Pifagor teoremasi', 2, 6),
  ((select id from t), 'Asosi 10, balandligi 6 bo‘lgan uchburchakning yuzi?', array['30', '15', '60', '16'], 0, 'S = 10 · 6 / 2 = 30.', 'Yuzalar', 1, 7),
  ((select id from t), 'Asosi 8, balandligi 5 bo‘lgan parallelogrammning yuzi?', array['13', '26', '40', '20'], 2, 'S = a · h = 40.', 'Yuzalar', 1, 8),
  ((select id from t), 'Diagonallari 6 va 8 bo‘lgan rombning yuzi?', array['24', '14', '12', '48'], 0, 'S = d₁ · d₂ / 2 = 24.', 'Yuzalar', 2, 9),
  ((select id from t), 'To‘rtburchak ichki burchaklarining yig‘indisi?', array['180°', '360°', '720°', '540°'], 1, null, 'To‘rtburchaklar', 1, 10),
  ((select id from t), 'Diametri 10 bo‘lgan doiraning yuzi?', array['100π', '5π', '10π', '25π'], 3, 'r = 5, S = πr² = 25π.', 'Aylana va doira', 2, 11),
  ((select id from t), 'Diametri 10 bo‘lgan aylananing uzunligi?', array['10π', '5π', '25π', '20π'], 0, 'C = πd = 10π.', 'Aylana va doira', 1, 12),
  ((select id from t), 'Diametrga tiralgan ichki chizilgan burchak necha gradus?', array['180°', '60°', '45°', '90°'], 3, null, 'Aylana va doira', 2, 13),
  ((select id from t), 'O‘xshash uchburchaklarning o‘xshashlik koeffitsiyenti 2 ga teng. Yuzalari nisbati?', array['8', '4', '2', '√2'], 1, 'Yuzalar nisbati k² ga teng.', 'O‘xshashlik', 3, 14),
  ((select id from t), 'Tomoni 4 bo‘lgan muntazam oltiburchakning perimetri?', array['20', '16', '36', '24'], 3, '6 · 4 = 24.', 'Ko‘pburchaklar', 1, 15);
with t as (insert into public.tests (title_uz, description_uz, subject, kind, grade, time_limit, source, sort_order, is_published)
  values ('Ingliz tili | 5-sinf: so‘zlar va oddiy grammatika', '5-sinf ingliz tili mavzulari: ranglar, sonlar, hafta kunlari va oylar, oila, to be / have got, Present Simple.', 'ingliz', 'mavzu', 5, 10, '14-maktab: fan dasturlari va darslik mavzulari asosida sayt uchun tuzilgan mashq savollari (2026, 2-qism). O‘qituvchilar tekshirib, to‘ldirib boradi.', 24, true) returning id)
insert into public.test_questions (test_id, question, options, correct, explanation, topic, difficulty, sort_order) values
  ((select id from t), '«Olma» in English is …', array['grape', 'apple', 'pear', 'orange'], 1, null, 'Vocabulary', 1, 1),
  ((select id from t), '«Qizil» in English is …', array['red', 'yellow', 'blue', 'green'], 0, null, 'Colours', 1, 2),
  ((select id from t), '«Twelve» — this number is …', array['2', '12', '20', '21'], 1, null, 'Numbers', 1, 3),
  ((select id from t), 'Which day comes after Monday?', array['Tuesday', 'Thursday', 'Sunday', 'Friday'], 0, null, 'Days and months', 1, 4),
  ((select id from t), 'The first month of the year is …', array['December', 'March', 'June', 'January'], 3, null, 'Days and months', 1, 5),
  ((select id from t), 'I ___ ten years old.', array['are', 'is', 'be', 'am'], 3, null, 'To be', 1, 6),
  ((select id from t), 'This is ___ umbrella.', array['a', 'an', 'the two', 'some'], 1, '«Umbrella» begins with a vowel sound.', 'Articles', 1, 7),
  ((select id from t), 'There ___ a cat in the room.', array['are', 'am', 'be', 'is'], 3, null, 'There is / are', 1, 8),
  ((select id from t), 'My sister ___ long hair.', array['is', 'have', 'are', 'has'], 3, null, 'Have got', 1, 9),
  ((select id from t), 'He ___ to school every day.', array['goes', 'going', 'go', 'gone'], 0, null, 'Present Simple', 2, 10),
  ((select id from t), 'The opposite of «hot» is …', array['warm', 'old', 'cold', 'big'], 2, null, 'Vocabulary', 1, 11),
  ((select id from t), '«Ona» in English is …', array['aunt', 'father', 'sister', 'mother'], 3, null, 'Family', 1, 12),
  ((select id from t), 'The plural of «box» is …', array['boxes', 'box', 'boxs', 'boxies'], 0, null, 'Nouns', 2, 13),
  ((select id from t), '«What''s your name?» — the best answer:', array['I am ten.', 'My name is Ali.', 'I am fine.', 'I live in Qiziriq.'], 1, null, 'Speaking', 1, 14),
  ((select id from t), 'I study ___ school number 14.', array['under', 'of', 'at', 'on'], 2, null, 'Prepositions', 2, 15);
commit;
