// Generated by scripts/make-mark.py — do not edit by hand.
//
// The school mark: a two-centred pointed arch with the numerals cut out of it and a gold
// keystone at the apex. One geometry, drawn the same on the site, in the app and on paper.
export const MARK_BOX = 64;
/** Tight box around the mark, so a parent sizes the arch itself rather than the air around it. */
export const MARK_VIEWBOX = "15.5 3 33 58";
export const MARK_ARCH = "M16.5 60V26.99A24.8 24.8 0 0 1 32 4A24.8 24.8 0 0 1 47.5 26.99V60Z";
export const MARK_KEYSTONE = "M25.187 8.138A24.8 24.8 0 0 1 32 4A24.8 24.8 0 0 1 38.813 8.138Z";
export const MARK_DIGITS = "M23.101 50.413V39.146H20.683V36.005Q21.854 36.005 22.615 35.594Q23.375 35.182 23.599 33.961H26.715V50.413ZM29.133 47.173V43.708Q30.355 42.287 31.302 40.991Q32.249 39.694 32.96 38.51Q33.67 37.326 34.169 36.18Q34.667 35.033 35.041 33.936H41.248V50.413H37.708V36.329H37.459Q36.836 37.875 36.076 39.233Q35.315 40.592 34.455 41.788Q33.595 42.985 32.648 44.082V44.331H43.517V47.173Z";
/** Base, springline and apex in box units — for anything that needs to align to the mark. */
export const MARK_GEOMETRY = { a: 15.5, base: 60, spring: 26.99, apex: 4 };
