# -*- coding: utf-8 -*-
"""Writes the school mark once, as SVG paths, so every surface draws the same shape.

The mark is a two-centred pointed arch — the gate of a school courtyard — with the numerals cut out
of it and a gold keystone at the apex. The geometry is a formula, not a drawing: half-width `a`,
centres offset `e = 0.6a` either side of the axis, radius `r = a + e`, so the two arcs lean into one
another and meet at a point `1.483a` above the springline.

The numerals come from the site's own display face (Bricolage Grotesque) and are baked into a path
here, so the mark never depends on a font being loaded.

Run after changing the geometry: python3 scripts/make-mark.py
"""
import math
from pathlib import Path

from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
FONT = ROOT / "assets/fonts/BricolageGrotesque-Bold.ttf"
OUT = ROOT / "src/components/mark.ts"

# The mark is drawn in a 64-wide box; everything below is derived from it.
BOX = 64
PAD = 4.0                     # the mark never touches the edge of its box
A = 15.5                      # half-width of the arch
E = 0.60 * A                  # how far the two centres sit from the axis
R = A + E
RISE = math.sqrt(R * R - E * E)               # springline to apex: 1.483 a
CX = BOX / 2
BASE = BOX - PAD
APEX = PAD
SPRING = APEX + RISE
SHAFT = BASE - SPRING         # jamb height, derived so the whole mark fits the box
CAP = APEX + (SPRING - APEX) * 0.18          # the keystone's lower edge
F = lambda v: f"{v:.3f}".rstrip("0").rstrip(".")


def arch_path() -> str:
    """Jamb, left arc to the apex, right arc down, jamb, closed."""
    return (
        f"M{F(CX - A)} {F(BASE)}V{F(SPRING)}"
        f"A{F(R)} {F(R)} 0 0 1 {F(CX)} {F(APEX)}"
        f"A{F(R)} {F(R)} 0 0 1 {F(CX + A)} {F(SPRING)}"
        f"V{F(BASE)}Z"
    )


def keystone_path() -> str:
    """The cap above CAP: the same two arcs, closed with a chord."""
    s = (SPRING - CAP) / R
    dx = R * math.cos(math.asin(s))
    return (
        f"M{F(CX + E - dx)} {F(CAP)}"
        f"A{F(R)} {F(R)} 0 0 1 {F(CX)} {F(APEX)}"
        f"A{F(R)} {F(R)} 0 0 1 {F(CX - E + dx)} {F(CAP)}Z"
    )


def digits_path(text: str = "14") -> str:
    """The numerals as one path, scaled to the shaft and centred on the axis.

    Drawn through a transform pen, so the glyph outlines come out already in box coordinates --
    glyph space is y-up, the box is y-down, hence the negative vertical scale.
    """
    font = TTFont(str(FONT))
    glyphs = font.getGlyphSet()
    cmap = font.getBestCmap()
    names = [cmap[ord(ch)] for ch in text]

    advance = sum(glyphs[n].width for n in names)
    scale = (2 * A * 0.78) / advance                     # the numerals fill 78% of the span

    bounds = BoundsPen(glyphs)
    for n in names:
        glyphs[n].draw(bounds)
    ymin, ymax = bounds.bounds[1], bounds.bounds[3]

    cy = SPRING + (BASE - SPRING) * 0.46                 # optical centre of the shaft
    oy = cy + (ymax + ymin) / 2 * scale
    ox = CX - advance * scale / 2

    out, x = [], 0.0
    for n in names:
        pen = SVGPathPen(glyphs, ntos=lambda v: F(v))
        glyphs[n].draw(TransformPen(pen, (scale, 0, 0, -scale, ox + x * scale, oy)))
        out.append(pen.getCommands())
        x += glyphs[n].width
    return "".join(out)


digits = digits_path()
OUT.write_text(
    "// Generated by scripts/make-mark.py — do not edit by hand.\n"
    "//\n"
    "// The school mark: a two-centred pointed arch with the numerals cut out of it and a gold\n"
    "// keystone at the apex. One geometry, drawn the same on the site, in the app and on paper.\n"
    f"export const MARK_BOX = {BOX};\n"
    "/** Tight box around the mark, so a parent sizes the arch itself rather than the air around it. */\n"
    f'export const MARK_VIEWBOX = "{F(CX - A - 1)} {F(APEX - 1)} {F(2 * A + 2)} {F(BASE - APEX + 2)}";\n'
    f'export const MARK_ARCH = "{arch_path()}";\n'
    f'export const MARK_KEYSTONE = "{keystone_path()}";\n'
    f'export const MARK_DIGITS = "{digits}";\n'
    "/** Base, springline and apex in box units — for anything that needs to align to the mark. */\n"
    f"export const MARK_GEOMETRY = {{ a: {F(A)}, base: {F(BASE)}, spring: {F(SPRING)}, apex: {F(APEX)} }};\n",
    encoding="utf-8",
)
print(f"mark written: a={A} shaft={SHAFT:.2f} spring={SPRING:.2f} apex={APEX:.2f} digits={len(digits)} chars")
